### ISSUE TITLE
热重载

### ISSUE THREAD

**Issue by sparrowhe** [takayama-lily/oicq#105]
不知道有没有热重载这个功能 希望以后能添加

**Comment by takayama-lily** [comment]
是指http-api的热重载？

**Comment by sparrowhe** [comment]
> 是指http-api的热重载？

指整个机器人的热重载，每次改代码都要ctrl+c再运行有点麻烦

**Comment by takayama-lily** [comment]
这只是一个lib，无法做到帮你重新加载整个node环境哦。
修改源代码之后，任何语言都几乎无法避免的需要重新编译和启动。
你可以考虑使用 [#http-api](https://github.com/takayama-lily/onebot) 通信来实现进程之间的隔离。

**Comment by undefined-moe** [comment]
请尝试使用nodemon
