### ISSUE TITLE
能否增加mac协议？

### ISSUE THREAD

**Issue by daofeng2015** [takayama-lily/oicq#106]
go-cqhttp已经有mac协议支持了，可能比pad,安卓更加完美，能否把设备信息做成配置文件，也方便修改

**Comment by takayama-lily** [comment]
设备信息文件一直都可以修改，在data/qq号/device.json。

mac和ipad可以添加(实验性)，长期使用可能还要观望。
Apple设备难分析，那边好像只改了一个数字版本号，其他参数是沿用安卓设备的。
最近出现的一些unknown login response(192, 139)不知道是否会和这个有关

**Comment by daofeng2015** [comment]
> 设备信息文件一直都可以修改，在data/qq号/device.json。
> 
> mac和ipad可以添加(实验性)，长期使用可能还要观望。
> Apple设备难分析，那边好像只改了一个数字版本号，其他参数是沿用安卓设备的。
> 最近出现的一些unknown login response(192, 139)不知道是否会和这个有关

隔壁的go-cqhttp已经支持了.实验性搞起来
