### ISSUE TITLE
手机版本过低的问题，基于Mirai框架所有的代码都会出现这个问题

### ISSUE THREAD

**Issue by ChinaMarsWT** [takayama-lily/oicq#108]

**Comment by takayama-lily** [comment]
现在密码正确也会版本过低吗？

**Comment by ChinaMarsWT** [comment]
是的，mirai已经更新了这个bug，提升了版本信息

**Comment by ChinaMarsWT** [comment]
这个问题只存在于新的用户，我在试着修改这个问题！

**Comment by ChinaMarsWT** [comment]
大佬最好您能看下，应为你俩的命名不太一样

**Comment by takayama-lily** [comment]
好的，我看一下

**Comment by ChinaMarsWT** [comment]
在昨天的更新版本中更改的，提交了两个版本parent 0888cd3

**Comment by ChinaMarsWT** [comment]
我没有使用他的版本，并不知道修改完毕之后有没有效果

**Comment by takayama-lily** [comment]
这个修改应该没什么用，只是更新了数字版本号和密钥协商方式(ECDH)。
可能tx改了什么东西，需要调查一下才能知道。

**Comment by ChinaMarsWT** [comment]
更新者说这可与你解决这个问题，其他的我也不是很清楚，有可能当前用的版本真的比较低？，使用phone登陆的时候，是禁止登陆的，提示让一件登陆。有可能他解决了这个问题，现在的问题是，新的用户使用软件的时候，都用不了。

**Comment by ChinaMarsWT** [comment]
就很难受

**Comment by takayama-lily** [comment]
更新了npm，大概率修复了。可以试一下。
至少在常用地应该没问题。记得开启设备锁。

**Comment by anaivebird** [comment]
mirai 2.0-M1现在还是没法登陆的
![image](https://user-images.githubusercontent.com/29398611/102689594-46e6cf80-423a-11eb-8e06-448f035454d0.png)

MiraiGo可以（修复的commit：https://github.com/Mrs4s/MiraiGo/commit/3a65d05f33782f6e6d3d00234f44ffd7660bea64）
oicq是可以登陆的

**Comment by takayama-lily** [comment]
目前已经支持滑动验证码，可彻底解决此问题。
相关参考： [#12](https://github.com/takayama-lily/onebot/issues/12) [#28](https://github.com/takayama-lily/onebot/issues/28)
