### ISSUE TITLE
[禁止登录]当前上网环境异常

### ISSUE THREAD

**Issue by wdssmq** [takayama-lily/oicq#115]
[禁止登录]当前上网环境异常，
请更换网络环境或在常用设备上登录或稍后再试。

**Comment by takayama-lily** [comment]
参考下readme中的 `登录常见问题`

**Comment by takayama-lily** [comment]
目前已经支持滑动验证码，可彻底解决此问题。
相关参考： [#12](https://github.com/takayama-lily/onebot/issues/12) [#28](https://github.com/takayama-lily/onebot/issues/28)
