### ISSUE TITLE
出现一次，无报错，消息接受不到。问题

### ISSUE THREAD

**Issue by ChinaMarsWT** [takayama-lily/oicq#116]
运行中，正常运行2天，突然就消息接受不到，网络稳定。无报错，无警告，重启解决。

**Comment by takayama-lily** [comment]
前几天突然我也遇到了，是安卓手机协议出现的。
总之在1.12中应该已经修复了。
如果再发生，或者如果你使用安卓协议平板出现此问题请告诉我。

**Comment by takayama-lily** [comment]
Over 4 months with no update, so I'm going to close this.
Feel free to ping me if this should be reopened.
