### ISSUE TITLE
在树莓派上nohup运行，ssh关闭后，自动关闭

### ISSUE THREAD

**Issue by anaivebird** [takayama-lily/oicq#117]
运行命令为nohup node main.js qq号 &

**Comment by takayama-lily** [comment]
你是不是没打exit退出，直接关闭了

**Comment by anaivebird** [comment]
用exit还是不行，所有ssh运行oicq都能有这个问题，还有我好像发错地方了，我用的是配套的onebot，不过oicq也有这个问题

**Comment by takayama-lily** [comment]
无法使用nohup可能是系统的问题，与nodejs程序无关。
你可以尝试其他工具，比如：
* screen
* pm2
* forever

**Comment by anaivebird** [comment]
我试试pm2把

**Comment by anaivebird** [comment]
pm2可以，是node.js的问题，网上老哥说了，nohup之类的方法都没用，只有pm2和forever可以
