### ISSUE TITLE
TX服务器抽风

### ISSUE THREAD

**Issue by 1438343098** [takayama-lily/oicq#120]
![image](https://user-images.githubusercontent.com/44186159/103326277-8c9d6680-4a8a-11eb-9a16-e3dc4c04acb0.png)

登录能接受信息然后不能发送一发送就掉线

**Comment by 1438343098** [comment]
一直重连后可以用了

**Comment by takayama-lily** [comment]
这两天tx某些服务器抽风，修改hosts解决，参考
https://github.com/takayama-lily/onebot/issues/12

**Comment by takayama-lily** [comment]
Over 4 months with no update, so I'm going to close this.
Feel free to ping me if this should be reopened.
