### ISSUE TITLE
更改了系统时间导致私聊信息收不到

### ISSUE THREAD

**Issue by grutty-sf** [takayama-lily/oicq#123]
![a](https://user-images.githubusercontent.com/29452099/104537347-c6f33000-5654-11eb-9087-6a699bee2c7e.png)

在core.js文件 里 this.msgExists()  这个函数一直continue。 是timestamp() - time >= 60了。是本地时间被我改了。  这里遇到了坑。
建议取消这个限制？ 或者优化下？

**Comment by takayama-lily** [comment]
qq有些地方设计很差，这里私聊很容易重复上报，目前是我能想到的最好方法。
改系统时间的需求也很少见，暂时你只能手动改一下了，
但是要注意私聊可能会重复上报，一些系统消息可能会触发不准确

**Comment by grutty-sf** [comment]
> qq有些地方设计很差，这里私聊很容易重复上报，目前是我能想到的最好方法。
> 改系统时间的需求也很少见，暂时你只能手动改一下了，比如
> 
> ```js
> bot.msgExists = () => false;
> ```
> 
> 但是要注意私聊可能会重复上报，一些系统消息可能会触发不准确
