### ISSUE TITLE
更新 1.12.6 后开启 debug 不间断弹出 emp 失败

### ISSUE THREAD

**Issue by dcyuki** [takayama-lily/oicq#125]
以前从没出现过这种情况，不知道为什么
![emp失败](https://user-images.githubusercontent.com/37479458/105372800-f3084580-5c40-11eb-8921-2e8225681557.png)

**Comment by takayama-lily** [comment]
部分账号刷新cookie失败会出现这个，原因还在调查
暂时不影响使用，除极个别依赖cookie的功能
