### ISSUE TITLE
aPad 群踢人不会触发 notice 事件

### ISSUE THREAD

**Issue by dcyuki** [takayama-lily/oicq#129]
之前一直是正常的，而且更新版本后主动退群 member 返回 undefined

**Comment by takayama-lily** [comment]
* 群员列表未加载的群，如果有人退群，member会返回undefined
（除非有人说话，或者主动获取才会加载
* 踢人不触发notice这个无法重现

**Comment by dcyuki** [comment]
> * 群员列表未加载的群，如果有人退群，member会返回undefined （群员列表是除非有人说话，或者主动获取才会加载
> * 踢人不触发notice这个无法重现
> 
> //最近新建了bug反馈群236172566，若有难以描述的问题可以加群



> * 群员列表未加载的群，如果有人退群，member会返回undefined
>   （群员列表是除非有人说话，或者主动获取才会加载
> * 踢人不触发notice这个无法重现
> 
> //最近新建了bug反馈群236172566，若有难以描述的问题可以加群

抱歉，我又测试了一会，是我的问题
因为昨天突然掉线提示风控，所以清理了下缓存把设备改成了 aPad 才遇到了上面的问题 orz
