### ISSUE TITLE
方不方便把node版本降到10或者6因为ubuntu以前的默认nodejs版本比较老

### ISSUE THREAD

**Issue by flameleo11** [takayama-lily/oicq#131]
挺好用的
升级了node12以后demo直接成功了

但是用ubuntu自带node 10会报错

![image](https://user-images.githubusercontent.com/6859207/107644861-f7110b80-6cb2-11eb-98b3-9f78d6400c43.png)

**Comment by takayama-lily** [comment]
不要，老版本很多语法和api不支持

**Comment by undefined-moe** [comment]
草这什么年代了还有人不用nvm

**Comment by flameleo11** [comment]
生气被鄙视了,

**Comment by undefined-moe** [comment]
建议找找还有哪些持续维护的库还在兼容node6的（

**Comment by flameleo11** [comment]
好多啊,iohook

**Comment by undefined-moe** [comment]
“Versions 0.4.X are the last to support for Node < 8.0 and Electron < 2.0.0”

**Comment by flameleo11** [comment]
不过提个问题,抛砖引玉1分钟学了个解决方案,我本来想装个docker用不同的版本,
没仔细查,已经有nvm解决了多版本共存的问题,
还是谢谢你了

**Comment by undefined-moe** [comment]
目前比较主流的应该是v12~v14，v15有点breaking change可能有小部分库不兼容

**Comment by flameleo11** [comment]
没事了,解决了
就跟python用venv一样
以后就不同项目用不同的node了

**Comment by flameleo11** [comment]
以后还要多问,每被鄙视一次
就跟赛亚人被打到一次一样,下次就变强了

**Comment by undefined-moe** [comment]
理论上来说目前用v12~v14没啥库跑不通的（（gyp除外

**Comment by flameleo11** [comment]
okay

**Comment by takayama-lily** [comment]
一些特别底层的库可能会兼容到很老的版本。
但是这个项目本身就艰难，不想再额外找麻烦了。
本来想直接放弃14以下版本的，目前不支持空安全的写法有点头疼。
考虑到win7好像无法运行14，兼容到12已经是折中选择了。
