### ISSUE TITLE
QQ机器人的QQ版本是不是太低了

### ISSUE THREAD

**Issue by xhemj** [takayama-lily/oicq#132]
场景：有时需要转发别人发的视频和图片消息
发现有部分消息显示`[视频]你的QQ暂不支持查看视频短片，请升级到最新版本后查看。`

**Comment by takayama-lily** [comment]
只是尚未实现视频收发，可能会在最近完成。(不用管文字提示

**Comment by xhemj** [comment]
ok，谢谢
