### ISSUE TITLE
关于同时登录多个id时,一次弹出很多bot的验证

### ISSUE THREAD

**Issue by flameleo11** [takayama-lily/oicq#133]
![image](https://user-images.githubusercontent.com/6859207/107954903-0d330a80-6fd8-11eb-845c-382f152f8a7a.png)
如果同时登录好多
一般是怎么解决这个问题,要手动一个个验证登录,还是?
![image](https://user-images.githubusercontent.com/6859207/107955128-613def00-6fd8-11eb-8139-912fc2764df4.png)

**Comment by takayama-lily** [comment]
新设备需要验证，这个绕不过
