### ISSUE TITLE
关于图片发送,怎么发送网络图片呢?是使用特别的接口sendimg(path)还是CQ协议文本?

### ISSUE THREAD

**Issue by flameleo11p** [takayama-lily/oicq#134]
![image](https://user-images.githubusercontent.com/76876582/108490693-fcd3a600-72dd-11eb-81a0-7e99ef236c75.png)
send发送格式如下
"[CQ:image,file=1.gif]" 

![image](https://user-images.githubusercontent.com/76876582/108490851-2987bd80-72de-11eb-8ad0-e0fd706b6af7.png)

**Comment by flameleo11p** [comment]
改成 相对于根目录的路径 "[CQ:image,file=data/image/2.jpg]"
ok了
怎么发送 网络图片 呢?

**Comment by takayama-lily** [comment]
直接填网址

**Comment by flameleo11p** [comment]
okay, 非常棒
