### ISSUE TITLE
发送音频 ffmpeg 提示无法转换  需要哪个版本的ffmpeg ?

### ISSUE THREAD

**Issue by flameleo11p** [takayama-lily/oicq#135]
![image](https://user-images.githubusercontent.com/76876582/108492185-cf87f780-72df-11eb-9624-bbc000a3e530.png)
"[CQ:record,file=data/record/gui.mp3]"

[2021-02-19T18:24:26.388] [WARN] [BOT:2114427834] - 音频转码到amr失败，请确认你的ffmpeg可以处理此转换。
[2021-02-19T18:24:26.389] [WARN] [BOT:2114427834] - 音频文件 data/record/gui.mp3 处理失败

**Comment by takayama-lily** [comment]
下载ffmpeg加入环境变量，或者自己通过其他途径转换成amr/silk格式的音频

**Comment by flameleo11p** [comment]
是不是还是 ffmpeg 版本的问题, ubuntu1804 LTS 默认带的 ffmpeg, 但是 encodes 里好像没有 amr的

**Comment by flameleo11p** [comment]
$ ffmpeg -version
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
这是版本信息

$ ffmpeg -encoders > ffmpeg_encodeers.txt
[ffmpeg_encodeers.txt](https://github.com/takayama-lily/oicq/files/6014919/ffmpeg_encodeers.txt)

里面好像没有 amr的解码器
不知道是ffmpeg 不对,还是要更新解码器?

**Comment by takayama-lily** [comment]
windows无问题，linux的ffmpeg不带amr，要自己重新编译加入amr_nb

**Comment by flameleo11p** [comment]
oh 原来如此
