### ISSUE TITLE
登录验证url，如何在一个无界面的linux上完成验证？

### ISSUE THREAD

**Issue by flameleo11p** [takayama-lily/oicq#136]
![image](https://user-images.githubusercontent.com/76876582/108700614-d2822280-7541-11eb-9b9e-3dfefb42cbee.png)

远程虚拟机配置了一个bot，登录
但是验证连接，本地浏览器打开，拖动滑动条后，重登陆，无法通过验证，还是打印出 slider 事件

**Comment by takayama-lily** [comment]
拖动后要把ticket取出来输入

**Comment by TheSnowfield** [comment]
使用Chromium打開此URL, 在獲得Ticket之後填入控制台.

**Comment by flameleo11p** [comment]
![image](https://user-images.githubusercontent.com/76876582/108719436-87283e00-755a-11eb-859f-c3397a95ff7c.png)
哦，之前也看到框架提示 ticket，但是不知道是啥，
这个 tickket 在哪里哪？我这个图上网页完成滑动条验证后，背景就变成全白了

**Comment by takayama-lily** [comment]
https://github.com/takayama-lily/node-onebot/issues/28

**Comment by flameleo11p** [comment]
原来如此，解决了

**Comment by flameleo11p** [comment]
登录的时候弹出手机扫码验证和滑动条验证可以自己控制吗？
还是平台决定的，随机的？

**Comment by takayama-lily** [comment]
陌生ip出现
