### ISSUE TITLE
登录以后，过一段时间，会收到下线通知

### ISSUE THREAD

**Issue by flameleo11p** [takayama-lily/oicq#137]
是需要设置每隔多长时间自动发一条消息
或者手动调用什么接口，心跳，保持连接吗？

![image](https://user-images.githubusercontent.com/76876582/108799907-92b44d00-75cc-11eb-9a09-13e3a6bd7b60.png)

**Comment by takayama-lily** [comment]
默认登录协议是手机，你是否有修改为pad

**Comment by flameleo11p** [comment]
没有修改源码，
可能是之前被顶掉了，申请了一个新的登录，就没问题了
连续两天没有重新登录

**Comment by takayama-lily** [comment]
应该是异地登录没有打开设备锁引起的
