### ISSUE TITLE
求一个上代理的思路

### ISSUE THREAD

**Issue by Cloud370** [takayama-lily/oicq#140]
用了挺久啦，只能说一个字 大佬牛逼！
开发大佬辛苦了!!!
每天看大佬的源码学习了好多！

求一个上代理的思路~
因为我1个IP挂多个机器人就有莫名其妙的风控~
所以我看了几天源码还是没搞明白在哪里封装代理比较好
因为我电脑又装不了docker，所以俺实在没办法了，球球了！

**Comment by takayama-lily** [comment]
xshell之类的ssh工具的端口转发应该就可以
msfwifi.3g.qq.com:8080映射到localhost:8080

**Comment by Cloud370** [comment]
> xshell之类的ssh工具的端口转发应该就可以
> msfwifi.3g.qq.com:8080映射到localhost:8080

想在代码里边集中处理代理逻辑可以吗，因为我是win +pm2 我太难了 TAT
还有顺便问一下大佬 用的是tcp还是udp呀？

**Comment by takayama-lily** [comment]
tcp,可直接转发数据包

**Comment by Cloud370** [comment]
> tcp,可直接转发数据包

大佬俺试了一下socks5
用的Proxifier+网上的第三方平台的代理
但是还是不行 我电脑上的几个TIM客户端重上也可以连上新的IP
如下图
![image](https://user-images.githubusercontent.com/46866207/110931094-d5b04780-8364-11eb-84f8-9e76dbb2aabc.png)
看到这里大佬辛苦了~

**Comment by undefined-moe** [comment]
请求支持`process.env.http_proxy` `process.env.https_proxy` `process.env.socks_proxy`（（

**Comment by Cloud370** [comment]
> 请求支持`process.env.http_proxy` `process.env.https_proxy` `process.env.socks_proxy`（（
首先谢谢大佬~

但是俺试了下 好像是真不行。。
 ```process.env.http_proxy```和```process.env.https_proxy``` 是proxy-agent里边带有的我知道
但是 ```socks_proxy```我试了也没用 查了下源码里边也没有 ```socks_proxy```相关的配置呀？
难道是我set变量的时候格式错了吗

**Comment by undefined-moe** [comment]
node似乎并不会自己认这几个env（（
需要代码手动处理的（）

**Comment by Cloud370** [comment]
> node似乎并不会自己认这几个env（（
> 需要代码手动处理的（）

那咋整 我是菜鸡 看不懂net

**Comment by undefined-moe** [comment]
我这边单ip挂三账号没有遇到任何问题倒是（
试试看挂久一点
我这边新号基本过一两个月就稳定了

**Comment by takayama-lily** [comment]
你需要设置config
```js
{
  remote_ip: 127.0.0.1,
  remote_port: 6498
}
```
