### ISSUE TITLE
私聊语音消息无 message_id 返回

### ISSUE THREAD

**Issue by Clansty** [takayama-lily/oicq#142]
Electron v11.3.0，Node v12.18.3，安卓手机协议

私聊语音消息无 message_id 返回

![image](https://user-images.githubusercontent.com/18461360/111070072-f74b3380-850a-11eb-8d6f-e36bc31e6b75.png)

**Comment by takayama-lily** [comment]
以前留的坑，不提都忘了，另外文件好像也没有

**Comment by Clansty** [comment]
对，文件也没有
