### ISSUE TITLE
发送语音失败

### ISSUE THREAD

**Issue by PromiseAll** [takayama-lily/oicq#145]
使用segment.record 提示函数未定义
![image](https://user-images.githubusercontent.com/56338627/112927291-55049000-9147-11eb-98bf-7efaa50b6b50.png)
![image](https://user-images.githubusercontent.com/56338627/112927364-72d1f500-9147-11eb-93e0-d7b314903337.png)

**Comment by takayama-lily** [comment]
使用`segment.ptt`, 应该有代码补全提示吧

**Comment by PromiseAll** [comment]
> 使用, 应该有代码补全提示吧`segment.ptt`

segment.ptt 也使用过它是不生效的，我把 图二中的case “record” 改成 “ptt”    segment.ptt 可正常发送

**Comment by takayama-lily** [comment]
这大概是bug。
修复之前手动构造吧
```js
{
  type: "record",
  data: {
    file: "xxx"
  }
}
```
