### ISSUE TITLE
将来会支持扫码吗？

### ISSUE THREAD

**Issue by Cloud370** [takayama-lily/oicq#150]
把自己QQ挂到了服务器，但是平时想上电脑端或者授权好麻烦呀，如果说将来会支持扫码的话那还能对接不少功能~

**Comment by takayama-lily** [comment]
扫码登录？可能会有吧。
不过对于机器人来说密码还是最好的，验证一次一劳永逸。
扫码登录在下线后再次登录时若凭证失效，可能需要重新扫码

**Comment by Cloud370** [comment]
> 扫码登录？可能会有吧。
> 不过对于机器人来说密码还是最好的，验证一次一劳永逸。
> 扫码登录在下线后再次登录时若凭证失效，可能需要重新扫码

还有能支持扫码授权类似qqmusic这种吗

**Comment by takayama-lily** [comment]
短期内大概不会支持这种

**Comment by Cloud370** [comment]
> 短期内大概不会支持这种

好的辛苦啦~ 是不是太麻烦了，我见过的授权形式就好几种哈哈哈
