### ISSUE TITLE
isOnline说机器人上线了，但sendGroupMsg说机器人没上线

### ISSUE THREAD

**Issue by AnnAngela** [takayama-lily/oicq#151]
* **你的操作系统**: Ubuntu 20.04.2 LTS (Focal Fossa) (x86_64) 5.4.0-71-generic

* **你的Node.js版本**: v14.16.1

* **使用的程序版本**: 1.15.1

* **使用的协议**: iPad

* [x] 我已确认过官方客户端不存在此问题，库的行为存在问题。

### 问题描述
我准备通过`proxy`来实现在发出消息前先检查机器人是否已经登录，这样能保证发送消息的成功率，但是按以下代码却出现矛盾的提示：
```js
const qq = 158****245;
const config = {
    platform: 5, //1:安卓手机 2:aPad 3:安卓手表 4:MacOS 5:iPad
};
process.mainModule = { path: process.cwd() };
const oicq = require("oicq").createClient(qq, config);
oicq.login(require("./secrets/qqbot.js")[qq]);
new Proxy(oicq, {
    get(t, p) {
        return (...args) => new Promise((res) => {
            console.info("t.isOnline()", 0, t.isOnline());
            if (t.isOnline()) {
                res();
            }
            const interval = setInterval(() => {
                if (t.isOnline()) {
                    console.info("t.isOnline()", 1, t.isOnline());
                    res();
                    clearInterval(interval);
                }
            }, 10);
        }).then(() => t[p](...args));
    },
}).sendGroupMsg(496034616, "ceshiceshi").then(c => console.info(true, c)).catch(c => console.info(false, c));
```
屏幕打印出来的却是：
```
[2021-04-15T11:43:17.198] [MARK] [BOT:158****245] - ----------
[2021-04-15T11:43:17.198] [MARK] [BOT:158****245] - Package Version: oicq@1.15.1 (Released on 2021/4/11)
[2021-04-15T11:43:17.198] [MARK] [BOT:158****245] - View Changelogs：https://github.com/takayama-lily/oicq/releases
[2021-04-15T11:43:17.198] [MARK] [BOT:158****245] - ----------
[2021-04-15T11:43:17.198] [MARK] [BOT:158****245] - connecting to msfwifi.3g.qq.com:8080
t.isOnline() 0 false
[2021-04-15T11:43:17.248] [MARK] [BOT:158****245] - 120.232.18.126:8080 connected
[2021-04-15T11:43:17.453] [MARK] [BOT:158****245] - Welcome, 低级机器人 ! 初始化资源...
t.isOnline() 1 true
true {
  retcode: 104,
  data: null,
  status: 'failed',
  error: { code: -1, message: 'bot not online' }
}
[2021-04-15T11:43:17.830] [MARK] [BOT:158****245] - 加载了5个好友，1个群。
[2021-04-15T11:43:17.831] [MARK] [BOT:158****245] - 初始化完毕，开始处理消息。
```
### 详细日志
*不知道为啥`log_level`设置成`debug`并不能打印更多的日志*

**Comment by Cloud370** [comment]
应该是异步的问题吧。。。

**Comment by Cloud370** [comment]
> 应该是异步的问题吧。。。

我都是直接加个`setTimeout` 懒得想那么多异步的问题，以前我也老纠结异步的问题，但是发现实际使用的时候，其实也不差这启动的几秒哈哈哈。

**Comment by AnnAngela** [comment]
但是我是先检查`isOnline`为真后再`resolve`最后才`sendGroupMsg`的










Ann丶Angela
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月15日(周四) 中午11:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [takayama-lily/oicq] isOnline说机器人上线了，但sendGroupMsg说机器人没上线 (#151)




 
应该是异步的问题吧。。。

**Comment by takayama-lily** [comment]
登录之后isOnline就会返回true，但是之后有个加载好友列表的过程，加载完成之前不允许调用api。
你在这个间隙里调用api，造成了两者不统一，今后应该会改进。
判断上线可以监听 `system.online` 事件，在这之后再进行调用。

**Comment by Cloud370** [comment]
> 但是我是先检查`isOnline`为真后再`resolve`最后才`sendGroupMsg`的 Ann丶Angela ***@***.***
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年4月15日(周四) 中午11:56 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [takayama-lily/oicq] isOnline说机器人上线了，但sendGroupMsg说机器人没上线 (#151) 应该是异步的问题吧。。。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你看源码还有个`sync_finished`的

**Comment by Cloud370** [comment]
> 登录之后isOnline就会返回true，但是之后有个加载好友列表的过程，加载完成之前不允许调用api。
> 你在这个间隙里调用api，造成了两者不统一，今后应该会改进。
> 判断上线可以监听 `system.online` 事件，在这之后再进行调用。

对了还有一个问题就是`log_level`除了`off`好像其他的不管用

**Comment by takayama-lily** [comment]
> 对了还有一个问题就是`log_level`除了`off`好像其他的不管用，
> 我自己封装了个自动滑块，当时想着屏蔽了自带的滑块log但是配置成`error`好像不管用，滑块验证不是`warn`吗

mark是最高等级的log，除了off无法屏蔽

**Comment by AnnAngela** [comment]
> > 对了还有一个问题就是`log_level`除了`off`好像其他的不管用，
> > 我自己封装了个自动滑块，当时想着屏蔽了自带的滑块log但是配置成`error`好像不管用，滑块验证不是`warn`吗
> 
> mark是最高等级的log，除了off无法屏蔽

他的意思是log_level不管用，我传入debug也不会显示debug日志

**Comment by AnnAngela** [comment]
> 登录之后isOnline就会返回true，但是之后有个加载好友列表的过程，加载完成之前不允许调用api。
> 你在这个间隙里调用api，造成了两者不统一，今后应该会改进。
> 判断上线可以监听 `system.online` 事件，在这之后再进行调用。

建议加入一个配置项（比如说`waitForOnline`），如果该配置项为真则所有异步操作都会先检测是否已经在线，如果离线就等待到在线后发出再返回（也可以再加一个timeout）

**Comment by AnnAngela** [comment]
如果作者觉得可以的话我晚上可以写一个pr

**Comment by Cloud370** [comment]
> > 登录之后isOnline就会返回true，但是之后有个加载好友列表的过程，加载完成之前不允许调用api。
> > 你在这个间隙里调用api，造成了两者不统一，今后应该会改进。
> > 判断上线可以监听 `system.online` 事件，在这之后再进行调用。
> 
> 建议加入一个配置项（比如说`waitForOnline`），如果该配置项为真则所有异步操作都会先检测是否已经在线且可执行，如果离线或因没有刷新好友列表等尚不可执行就等待到在线且可执行后发出操作再返回（也可以再加一个timeout）

 我觉得作者没必要写一个方法呀，你现在`bot.sync_finished` 用`setInterval`和`Promise`自己实现一个

**Comment by takayama-lily** [comment]
> 建议加入一个配置项（比如说`waitForOnline`），如果该配置项为真则所有异步操作都会先检测是否已经在线且可执行，如果离线或因没有刷新好友列表等尚不可执行就等待到在线且可执行后发出操作再返回（也可以再加一个timeout）

这个再说吧，感觉会引发别的问题。

**Comment by Cloud370** [comment]
我觉得这个功能真的是看需求的，大部分人不会有在加载列表的时候就发出消息的需求，有需求的人大部分也会看源码然后监听`system.online`之后再发

**Comment by takayama-lily** [comment]
这个间隙的问题应该不是很重要，也不太方便改，先关闭了。
