### ISSUE TITLE
首次登录问题

### ISSUE THREAD

**Issue by Cloud370** [takayama-lily/oicq#153]
首次登录的时候，安卓端按道理来说不应该是有短信验证的选项吗？
还是oicq默认选择了二维码验证的方式呀？
只是好奇但是如果有短信验证就更好了，因为有手机不在身边的需求
如果要加的话很麻烦就算了，哈哈哈。 
另外 作者更新辛苦了~
真的每天最期待的就看oicq的commit了

**Comment by takayama-lily** [comment]
没做。
