### ISSUE TITLE
bot 时不时地收不到私聊消息

### ISSUE THREAD

**Issue by JeffGe05** [takayama-lily/oicq#167]
* **你的操作系统**: Linux version 3.10.102

* **你的Node.js版本**: v14.16.0

* **使用的程序版本**: v1.17.2

* **使用的协议**: 手机(默认)

* [x] 我已确认过官方客户端不存在此问题，库的行为存在问题。

### 问题描述
我和 bot 是双向好友，给 bot 发送私聊消息，后台确认没有收到，该现象以前未发现过，这段时间高频出现，私聊已经处于是偶尔才能收到的状态。用最新版的 PC QQ 登录 bot 账号能收到所有私聊消息。群聊消息暂未发现丢失现象。

我没有用库内置的 debug 模式查看消息收发状态，主程序监听 `"message"` 事件并把所有 `data: MessageEventData` 用 `JSON.stringify` 原样保存，从保存的数据中确认没有收到。

**Comment by takayama-lily** [comment]
#123 看看会不会是因为这个(系统时间不对

**Comment by JeffGe05** [comment]
是的，我把系统时间 NTP 同步之后就好了，谢谢！
