### ISSUE TITLE
部分情况下 Array 方式上报会有 null 出现的问题

### ISSUE THREAD

**Issue by anaivebird** [takayama-lily/oicq#182]
* **你的操作系统**: win10

* **你的Node.js版本**: v14.16.0

* **使用的程序版本**: v1.17.3

* **使用的协议**: 手机(默认)

### 问题描述

nonebot2那边报错和这个一模一样
https://github.com/nonebot/nonebot2/issues/325

这个issue里给出的解决方法是：
“go-cqhttp v1.0.0-beta3 版本修复了这个问题，可能是 Array 上报部分字段为 null 导致的”
请问是不是oicq也有类似于go-cqhttp的问题
参考https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-beta3中的“修复: 部分情况下 Array 方式上报会有 null 出现的问题. by @wdvxdr1123”

**Comment by takayama-lily** [comment]
需要更多信息

**Comment by anaivebird** [comment]
安装最新版node-onebot（https://github.com/takayama-lily/node-onebot）和nonebot2并登录使用即可复现这个bug（也就是说oicq和nonebot2无法兼容）
而旧版nonebot==2.0.0a7却可以和node-onebot兼容

**Comment by takayama-lily** [comment]
这边消息元素不可能为null，应该是nonebot自身的问题
