### ISSUE TITLE
如何使用插件，制作机器人

### ISSUE THREAD

**Issue by 448808614** [takayama-lily/oicq#185]
你的操作系统: termux
你的Node.js版本:14.17.3
使用的程序版本: 最新版本
使用的协议: 手机(默认)
问题描述:
如何使用插件，制作机器人
目前只会send target msg发送消息
详细日志:

**Comment by takayama-lily** [comment]
[abot](https://github.com/takayama-lily/abot) 是一个基于此库开发的插件式的机器人，完全通过QQ消息来管理，支持多账号并行，制作插件也比较简单。
好处在于使用QQ本身作为控制台远程控制，可以一键在后台运行，不用维护复杂的UI界面。
登录多个账号后，若其中一个账号出现意外情况，其他账号会及时发消息通知你。
