### ISSUE TITLE
请问是否支持代理登陆

### ISSUE THREAD

**Issue by simo8102** [takayama-lily/oicq#191]
请问是否支持代理登陆
因为有部分项目会返回一些需要代理得一些图片地址
而oicq去请求这个地址的时候就会导致无法请求

如果支持得话我应该怎么去设置使用它

**Comment by takayama-lily** [comment]
你是指发图片吗？这种时候建议自行下载图片，不要使用网络url了。

**Comment by simo8102** [comment]
> 你是指发图片吗？这种时候建议自行下载图片，不要使用网络url了。

由于项目特性只能返回url  
希望后期能支持代理登陆

**Comment by JeffGe05** [comment]
> > 你是指发图片吗？这种时候建议自行下载图片，不要使用网络url了。
> 
> 由于项目特性只能返回url
> 希望后期能支持代理登陆

你拿到 URL 了自己通过代理下载就行了，把得到的 Buffer 放 segment.image 里面发送就行了：`client.sendGroupMsg(123456, segment.image(buffer))`
