### ISSUE TITLE
能否强制使用分片发送

### ISSUE THREAD

**Issue by 71e6fd52** [takayama-lily/oicq#193]
* **你的操作系统**: Arch Linux

* **你的Node.js版本**: v16.6.1

* **使用的程序版本**: oicq 1.18.3, node-onebot 1.3.0

* **使用的协议**: ipad

* [x] 我已确认过官方客户端不存在此问题，库的行为存在问题。

### 问题描述

这边短消息发送显示被风控，长消息发送失败自动转为分片发送后却能成功发送。

### 详细日志
```
8月 09 17:09:58 archlinux node[410144]: [2021-08-09T17:09:58.229] [INFO] [iPad:******] - recv from: [Group: ******, Member: ******] .rd20劣势+d4+2
8月 09 17:10:03 archlinux node[410144]: [2021-08-09T17:10:03.557] [ERROR] [iPad:******] - send failed: [Group: ******] 群消息可能发送失败，请检查消息内容。
8月 09 17:10:34 archlinux node[410144]: [2021-08-09T17:10:34.267] [INFO] [iPad:******] - recv from: [Group: ******, Member: ******] .help
8月 09 17:10:34 archlinux node[410144]: [2021-08-09T17:10:34.869] [WARN] [iPad:******] - 群消息被风控，将尝试使用分片发送。
8月 09 17:10:35 archlinux node[410144]: [2021-08-09T17:10:35.064] [INFO] [iPad:******] - send to: [Group: ****** / message_id: MOupdFoix60AAAjqkiCF1mEQ8QsE]
```

**Comment by takayama-lily** [comment]
可以考虑缩小分片，目前一个分片是80个字，被风控的消息长度是多少？可以的话希望提供消息原文。
目前风控机制很奇怪，有时候很短的消息也风控，如果消息太短则不适合分片。

**Comment by 71e6fd52** [comment]
测试下来是超过2个字节的群消息都无法发送，但是只要是分片消息就可以发送。

**Comment by takayama-lily** [comment]
2字节的问题其实是另一种风控（tx认为此次登录不安全），一般挂机几天就可以解除，重启也可短暂解除。
> 也有一说改密码可解除但没测试过

**Comment by 71e6fd52** [comment]
分片消息就可以发送，所以是不是可以通过分片发送所有的消息来解决

**Comment by takayama-lily** [comment]
> 分片消息就可以发送，所以是不是可以通过分片发送所有的消息来解决

分片只是把超过80字的消息分成多条发送，，所以80字以下分不分片并无不同。
一般不可能出现2个字无法发送时，80字却可以发送的情况。你确定这是真实发生的吗？

**Comment by 71e6fd52** [comment]
是，现在就是超过 80 字能正常发送，80 字以下不能发送

**Comment by takayama-lily** [comment]
> 是，现在就是超过 80 字能正常发送，80 字以下不能发送

我这有风控号，但从未遇到过这么离奇的问题。
是否所有超过2字节，小于80字的都无法发送？如果不是的话，能否给一段(被风控的)具体消息内容

**Comment by 71e6fd52** [comment]
是，所有。这是一个骰娘，消息就长这样 ”吉洛塔 掷出了 D20=19“。

BTW，我是挂在阿里云 HK 的服务器上，不知道和 ip 有没有关系。
