### ISSUE TITLE
AGPL-3.0 协议并不禁止商用

### ISSUE THREAD

**Issue by Shigma** [takayama-lily/oicq#2]
https://choosealicense.com/licenses/agpl-3.0/

GPL-3.0 的最显著特点是【衍生作品需使用同协议开源】，AGPL-3.0 相比 GPL-3.0 主要的区别是【通过网络的使用属于传播】，两者都不限制商用，因此 README 中的表达有误。

如果希望禁止商用，建议作者通过附加条款的方式加以限制。

**Comment by takayama-lily** [comment]
本意就不完全禁止。修改了一下用词。
