### ISSUE TITLE
请问如何监听加入新群的事件

### ISSUE THREAD

**Issue by Arondight** [takayama-lily/oicq#201]
例如 bot 正在运行中，我用 qq 客户端手动加入了一个群，bot 如何判断有群列表新增了一个群？我找了找没有找到相关的事件。

https://github.com/takayama-lily/oicq/blob/0961154c564234befcf906c23fdcb02713436142/index.d.ts#L970-L998

**Comment by takayama-lily** [comment]
目前这种情况好像没有事件上报，只有被管理员邀请入群才有事件。
以前酷Q时代好像也有这个问题，一直没有对应。

**Comment by Arondight** [comment]
我看代码已经更新了，事件`85`也被对应到了`group.increase`，但是从最终用户的视角上看，似乎和以前并无区别，因为还是分不清这个事件究竟是群员增加了，还是机器人被拉入群了。

**Comment by takayama-lily** [comment]
> 我看代码已经更新了，事件`85`也被对应到了`group.increase`，但是从最终用户的视角上看，似乎和以前并无区别，因为还是分不清这个事件究竟是群员增加了，还是机器人被拉入群了。

机灵一点，判断user_id是不是你自己

**Comment by Arondight** [comment]
有道理
