### ISSUE TITLE
[建议加入] API 加入 处理群申请事件

### ISSUE THREAD

**Issue by MisaLiu** [takayama-lily/oicq#208]
翻了下 Plan 和 Wiki，似乎没有该 API 的相关文档/信息？

希望后续能有对该 API 的支持，还是比较有用的

**Comment by ura-account** [comment]
https://github.com/takayama-lily/oicq/blob/29824bd2715cf936d4ac0a311f713593fe641cfc/index.d.ts#L876-L877
