### ISSUE TITLE
帐号或密码错误

### ISSUE THREAD

**Issue by Keanu-42** [takayama-lily/oicq#213]
## Describe the bug / 描述

- 在帐号和密码无误的情况下，一直提示错误

## To Reproduce / 复现过程

- 我用另一个帐号登录是没有问题的，只有这个帐号报错，我在手机端重新登录是确认了帐号和密码无误

## System information / 系统信息

 - OS: Manjaro Gnome 40
 - Program Version: 1.19.5
 - Node.js Version: 16.7.0-1
 - Agreement: defalut

## Additional context / 附加信息

- 我用的是长密码，在官方客户端中密码长度是超出了输入框的
- 已尝试过使用**32位小写md5**密码登录
- 使用的客户端：[Clansty/Icalingua](https://github.com/Clansty/Icalingua)(lastest)

**Comment by ura-account** [comment]
你的密码有多个字符？

**Comment by Keanu-42** [comment]
> 你的密码有多个字符？

20个

**Comment by Keanu-42** [comment]
> 你的密码有多个字符？

请问问题是出在这里吗？

**Comment by takayama-lily** [comment]
> > 你的密码有多个字符？
> 
> 请问问题是出在这里吗？

不知道呢，现在好像没法设置超过16个字的，要不你改短点试试

**Comment by Keanu-42** [comment]
> > > 你的密码有多个字符？
> > 
> > 
> > 请问问题是出在这里吗？
> 
> 不知道呢，现在好像没法设置超过16个字的，要不你改短点试试

好吧，谢谢！
