### ISSUE TITLE
转发消息中包含文件时无法正常解析

### ISSUE THREAD

**Issue by takayama-lily** [takayama-lily/oicq#216]
无论是私聊文件还是群文件
来自Clansty/Icalingua#189

**Comment by Clansty** [comment]
草，所以现在遇到文件是直接跳过了

**Comment by takayama-lily** [comment]
> 草，所以现在遇到文件是直接跳过了

是啊，之前有一条解不出就没了。现在解不出的跳过，不影响别后面的。
