### ISSUE TITLE
登录保护二维码验证加载不出来怎么办

### ISSUE THREAD

**Issue by chinoll** [takayama-lily/oicq#218]
在滑块验证之后的扫描二维码阶段，用chrome和QQ客户端都没办法刷新出二维码，请问如何解决
![QQ截图20210910161515](https://user-images.githubusercontent.com/22575232/132822675-1714fb39-3352-4ae0-bd6d-b9d381abd288.png)

**Comment by takayama-lily** [comment]
不知道，比较少见，可以试试短信验证，在扫码阶段使用这两个方法
`client.sendSMSCode` `client.submitSMSCode`

**Comment by chinoll** [comment]
> 不知道，比较少见，可以试试短信验证，在扫码阶段使用这两个方法
> `client.sendSMSCode` `client.submitSMSCode`

谢谢，已经解决

**Comment by 1742035356** [comment]
启动时提示登陆保护，然后打开地址提示设备授权校验失败，请退出流程后重新进入
![image](https://user-images.githubusercontent.com/99705099/187974395-af5d5ab8-6275-4ab0-8906-65223fe14dad.png)
![image](https://user-images.githubusercontent.com/99705099/187974562-512f5140-34c0-4e49-a334-eef0b0f77d6d.png)
