### ISSUE TITLE
请求支持在线状态的查询

### ISSUE THREAD

**Issue by goodspeed34** [takayama-lily/oicq#221]
能否支持在线状态的查询？现在貌似只能查看自身的在线状态。

希望好友信息和群友信息里可以包含在线状态。

**Comment by takayama-lily** [comment]
移动时代真的需要这个吗

**Comment by Cloud370** [comment]
> 移动时代真的需要这个吗

如果获取到的是准确的话的确需要

**Comment by takayama-lily** [comment]
https://github.com/takayama-lily/oicq/blob/main/demo/get-friend-online-status.js
