### ISSUE TITLE
【功能反馈】关于「合并转发自定义节点」的实现

### ISSUE THREAD

**Issue by SilveryStar** [takayama-lily/oicq#222]
在 `OneBot v11` 中的消息段类型中，有[自定义节点功能](https://github.com/botuniverse/onebot/blob/master/v11/specs/message/segment.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9)，这可以很好的避免当 Bot 存在较多返回内容时的刷屏问题，希望可以添加这个在合并转发中使用自定义节点的功能，而非需要真实的消息

**Comment by takayama-lily** [comment]
可安排

**Comment by TheSnowfield** [comment]
> 可安排

我有一点此功能在未来是否可用的担忧, 毕竟它本身就是合理地滥用,
并不排除在未来可能会被取缔或检测.

**Comment by takayama-lily** [comment]
@TheSnowfield 但确实把大段内容丢到转发里是挺不错的

**Comment by TheSnowfield** [comment]
> @TheSnowfield 但确实把大段内容丢到转发里是挺不错的

确实不错，但是我不确定此功能会不会在未来失效
