### ISSUE TITLE
有没有开关关闭INFO信息和二维码保存

### ISSUE THREAD

**Issue by anaivebird** [takayama-lily/oicq#223]
* **你的操作系统**: win10?

* **你的Node.js版本**:  v14.16.0

* **使用的程序版本**: v1.20.2

* **使用的协议**: 手表

* [x] 我已确认过官方客户端不存在此问题，库的行为存在问题。

### 问题描述
有没有开关开关关闭[INFO] [ERROR]等信息
有没有开关，选择不保存二维码图片文件：
“请用手机QQ扫描二维码，若打印出错请打开：/home/huan/git/naivebird/wechaty-getting-started/data/12345/qrcode.png”

谢谢！

**Comment by takayama-lily** [comment]
1.修改日志等级
2.自行删除

**Comment by anaivebird** [comment]
请问在哪里修改日志等级呢？有没有文档链接

**Comment by takayama-lily** [comment]
> 请问在哪里修改日志等级呢？有没有文档链接

创建实例的时候，看d.ts
