### ISSUE TITLE
v2.x投票问卷

### ISSUE THREAD

**Issue by takayama-lily** [takayama-lily/oicq#229]
> 调查结果将作为2.0版本的制作基础

### 你是否还在使用CQ码字符串发消息或解析消息

[![](https://api.gh-polls.com/poll/01FJVPJMX75MDRYNDYT83XW3T7/yes)](https://api.gh-polls.com/poll/01FJVPJMX75MDRYNDYT83XW3T7/yes/vote)
[![](https://api.gh-polls.com/poll/01FJVPJMX75MDRYNDYT83XW3T7/no)](https://api.gh-polls.com/poll/01FJVPJMX75MDRYNDYT83XW3T7/no/vote)

### 你偏好什么样风格的API

[![](https://api.gh-polls.com/poll/01FH6JJBW203HBPRX9KD6PJFJ3/%E7%9B%AE%E5%89%8D%E8%BF%99%E7%A7%8D%EF%BC%9AsendGroupMsg(gid%2C%20msg))](https://api.gh-polls.com/poll/01FH6JJBW203HBPRX9KD6PJFJ3/%E7%9B%AE%E5%89%8D%E8%BF%99%E7%A7%8D%EF%BC%9AsendGroupMsg(gid%2C%20msg)/vote)
[![](https://api.gh-polls.com/poll/01FH6JJBW203HBPRX9KD6PJFJ3/%E6%9B%B4%E5%8A%A0%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1%E7%9A%84%EF%BC%9Agroup.sendMsg(msg))](https://api.gh-polls.com/poll/01FH6JJBW203HBPRX9KD6PJFJ3/%E6%9B%B4%E5%8A%A0%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1%E7%9A%84%EF%BC%9Agroup.sendMsg(msg)/vote)

### 你偏好什么样风格的API返回值

[![](https://api.gh-polls.com/poll/01FH6K88Q0VYRSPGNFHT20Z6ZM/%E7%9B%AE%E5%89%8D%E8%BF%99%E7%A7%8D%EF%BC%8C%E8%BF%94%E5%9B%9E%20Promise%3C%7B%20retcode%3A%200%2C%20data%3A%20...%20%7D%3E)](https://api.gh-polls.com/poll/01FH6K88Q0VYRSPGNFHT20Z6ZM/%E7%9B%AE%E5%89%8D%E8%BF%99%E7%A7%8D%EF%BC%8C%E8%BF%94%E5%9B%9E%20Promise%3C%7B%20retcode%3A%200%2C%20data%3A%20...%20%7D%3E/vote)
[![](https://api.gh-polls.com/poll/01FH6K88Q0VYRSPGNFHT20Z6ZM/%E7%9B%B4%E6%8E%A5%E8%BF%94%E5%9B%9E%20Promise%3Cdata%3E%20%EF%BC%8C%E6%88%91%E8%87%AA%E5%B7%B1%E6%9D%A5catch%E5%BC%82%E5%B8%B8)](https://api.gh-polls.com/poll/01FH6K88Q0VYRSPGNFHT20Z6ZM/%E7%9B%B4%E6%8E%A5%E8%BF%94%E5%9B%9E%20Promise%3Cdata%3E%20%EF%BC%8C%E6%88%91%E8%87%AA%E5%B7%B1%E6%9D%A5catch%E5%BC%82%E5%B8%B8/vote)

### 你偏好什么样风格的消息元素形式

[![](https://api.gh-polls.com/poll/01FH6JYP33BAYB249TG6968S6H/%E7%9B%AE%E5%89%8D%E8%BF%99%E7%A7%8D%EF%BC%9A%7B%20type%3A%20%22face%22%2C%20data%3A%20%7B%20id%3A%20123%20%7D%20%7D)](https://api.gh-polls.com/poll/01FH6JYP33BAYB249TG6968S6H/%E7%9B%AE%E5%89%8D%E8%BF%99%E7%A7%8D%EF%BC%9A%7B%20type%3A%20%22face%22%2C%20data%3A%20%7B%20id%3A%20123%20%7D%20%7D/vote)
[![](https://api.gh-polls.com/poll/01FH6JYP33BAYB249TG6968S6H/%E6%89%81%E5%B9%B3%E5%BD%A2%E5%BC%8F%EF%BC%9A%7B%20type%3A%20%22face%22%2C%20id%3A%20123%20%7D)](https://api.gh-polls.com/poll/01FH6JYP33BAYB249TG6968S6H/%E6%89%81%E5%B9%B3%E5%BD%A2%E5%BC%8F%EF%BC%9A%7B%20type%3A%20%22face%22%2C%20id%3A%20123%20%7D/vote)

**Comment by PluginsKers** [comment]
各项指代？

**Comment by dcyuki** [comment]
![好耶](https://gchat.qpic.cn/gchatpic_new/2225151531/521380411-2534853825-5651AB5B736AC545A1C2FC3BD8792405/0)
