### ISSUE TITLE
探索可用服务器,探索服务器失败 The Iterable argument must be og type iterable 。The "chunk" argument must be one of type string, 

### ISSUE THREAD

**Issue by 468336329Zc** [takayama-lily/oicq#231]
### Node.js Version

12.8.0 && 14.18.0 && 16.6.1

### Package Version

yarn v1.22.15

### Bug Description

之前找到过相似报错，说是node版本问题，
但我这个用了node 12.8 14 16版都不可以。。

### Log Details

![image](https://user-images.githubusercontent.com/49133904/136353136-f36abd29-0b9e-4624-98a4-9130bc3488d2.png)

**Comment by takayama-lily** [comment]
大概是你切换的版本没生效
