### ISSUE TITLE
data_dir路径的拼接问题

### ISSUE THREAD

**Issue by youliso** [takayama-lily/oicq#245]
### Node.js Version

16.5.0

### Package Version

1.21.2

### Bug Description

![image](https://user-images.githubusercontent.com/34784062/138587153-2c84e2cc-7b14-4f48-927a-35e0ca629d1f.png)
`oicq/lib/client.js:156` 处，如果已经指定data_dir基本上是绝对路径，建议不要进行拼接。

### Log Details

(node:35152) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:370:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:429:7)
    at new Client (webpack-internal:///./node_modules/oicq/lib/client.js:156:28)
    at createClient (webpack-internal:///./node_modules/oicq/index.js:33:12)
    at qqOn (webpack-internal:///./src/core/qq/main.ts:12:65)
    at eval (webpack-internal:///./src/main/index.ts:38:54)
(Use `electron --trace-warnings ...` to show where the warning was created)
[main stderr 下午4:47:04]: (node:35152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by youliso** [comment]
我的意思就是改成这样
![image](https://user-images.githubusercontent.com/34784062/139693356-bbdb681c-fa6d-4f54-9f56-365c3cb244d4.png)

**Comment by takayama-lily** [comment]
一直都可以这么用！
