### ISSUE TITLE
可以为 v1.x 拉一个分支吗？

### ISSUE THREAD

**Issue by Arondight** [takayama-lily/oicq#250]
### Bug Description

希望从 1.x 最后一个 commit 拉一个 1.x 的分支，看代码方便一些。

**Comment by takayama-lily** [comment]
看master分支就行了

**Comment by Arondight** [comment]
啊这，master 不是 2.x 的代码了吗

**Comment by Arondight** [comment]
> 
> 
> 啊这，master 不是 2.x 的代码了吗

我知道了， main 是 2.x ， master 是 1.x ，我感觉是不是把 master 改个名字比较好，这样容易出现混淆

**Comment by Arondight** [comment]
@takayama-lily 另外我想问一下 1.x 计划支持多久，目前我用的 1.x 但是不想更新到 2.x 上去

**Comment by takayama-lily** [comment]
> @takayama-lily 另外我想问一下 1.x 计划支持多久，目前我用的 1.x 但是不想更新到 2.x 上去

只要tx不改协议估计可以一直使用。
