### ISSUE TITLE
请问正确向nonebot推送消息的方法

### ISSUE THREAD

**Issue by retroxz** [takayama-lily/oicq#251]
### Node.js Version

16.13.0

### Package Version

1.21.2

### Login Protocol

Android

### Bug Description

使用oicq向nonebot推送消息时 任何消息nonebot都无法解析 
提示：ValueError: Event has no message!
因为搞不太懂是哪边的配置出了问题所以在两边都发了issue
详见https://github.com/nonebot/nonebot2/issues/583
谢谢

oicq配置如下

`
general: {
        platform:           1,       //1:安卓手机 2:aPad 3:安卓手表 4:MacOS 5:iPad
        log_level:          "info",  //trace,debug,info,warn,error,mark
        use_cqhttp_notice:  true,   //是否使用cqhttp标准的notice事件格式

        host:               "0.0.0.0",  //监听主机名
        port:               5700,       //端口
        use_http:           false,      //启用http
        use_ws:             false,      //启用正向ws，和http使用相同地址和端口
        access_token:       "",         //访问api的token
        secret:             "",         //上报数据的sha1签名密钥
        post_timeout:       30,         //post超时时间(秒)
        post_message_format:"array",    //"string"或"array"
        enable_cors:        false,      //是否允许跨域请求
        enable_heartbeat:   false,      //是否启用ws心跳
        heartbeat_interval: 15000,      //ws心跳间隔(毫秒)
        rate_limit_interval:500,        //使用_rate_limited后缀限速调用api的排队间隔时间(毫秒)
        event_filter:       "",         //json格式的事件过滤器文件路径
        post_url: [ //上报地址，可以添加多个url
            // "http://your.address.com:80",
        ],
        ws_reverse_url: [ //反向ws地址，可以添加多个url
            "ws://127.0.0.1:1885/cqhttp/ws"
        ],
        ws_reverse_reconnect_interval: 3000, //反向ws断线重连间隔(毫秒)，设为负数直接不重连
        ws_reverse_reconnect_on_code_1000: true, //反向ws是否在关闭状态码为1000的时候重连
    },`

_No response_

**Comment by takayama-lily** [comment]
可能是message_id吧，据说nonebot不认字符串形式的的message_id

**Comment by mnixry** [comment]
> 可能是message_id吧，据说nonebot不认字符串形式的的message_id

是这样的, 在NoneBot2中, 我们会尝试将`message_id`序列化成int类型, 但是由于node-onebot上报的`message_id`字段为str类型, 我们无法对其进行正确的序列化操作, 这会使事件回退到基类. 这是导致 @retroxz 故障发生的原因

无论在技术上实现如何, OneBot v11标准确实已经规定了`message_id`的字段类型为`int`. 所以为了保证和其他SDK的兼容, 我们希望您考虑对其进行一定的处理

**Comment by retroxz** [comment]
@takayama-lily @mnixry  谢谢大佬解答
