### ISSUE TITLE
密码登陆一直length of encrypted data must be a multiple of 8

### ISSUE THREAD

**Issue by MaoSource** [takayama-lily/oicq#261]
密码登陆一直length of encrypted data must be a multiple of 8
![image](https://user-images.githubusercontent.com/56857029/145181034-919aca50-4ed8-404b-8fcf-02a5891888cc.png)

**Comment by TheSnowfield** [comment]
應該是登錄包的問題, 排查中

**Comment by TheSnowfield** [comment]
#260

**Comment by MaoSource** [comment]
> 應該是登錄包的問題, 排查中

好的

**Comment by TheSnowfield** [comment]
嘗試一下 https://github.com/TheSnowfield/oicq
如問題得到修復則更新到主分支
