### ISSUE TITLE
ipad 登录出现报错

### ISSUE THREAD

**Issue by ChinaMars521** [takayama-lily/oicq#266]
### Node.js Version

14.0

### Package Version

是的

### Login Protocol

iPad

### Bug Description

登录出错，请看报错日志

### Log Details

 [ERROR] [iPad:3497628268] - length of encrypted data must be a multiple of 8
 [ERROR] [iPad:3497628268] - length of encrypted data must be a multiple of 8
 [ERROR] [iPad:3497628268] - length of encrypted data must be a multiple of 8
 [ERROR] [iPad:3497628268] - length of encrypted data must be a multiple of 8
 [ERROR] [iPad:3497628268] - length of encrypted data must be a multiple of 8

**Comment by ChinaMars521** [comment]
oicq更新之后频繁要我二维码登录 扫完之后生成提示二维码过期

**Comment by ChinaMars521** [comment]
pm2 启动变成手表登录

**Comment by ChinaMars521** [comment]
麻了

**Comment by Cloud370** [comment]
麻烦提供一下oicq的版本号

**Comment by ChinaMars521** [comment]
npm 最新版

**Comment by ChinaMars521** [comment]
二维码登录失效

**Comment by ChinaMars521** [comment]
更新完不提示length of encrypted data must be a multiple of 8 让我扫二维码，使用的是默认的协议，扫描二维码谈出手表登录，扫完之后无反应。重新扫描二维码失效。

**Comment by ChinaMars521** [comment]
![image](https://user-images.githubusercontent.com/76717950/145774510-dfdd2472-038d-4c43-83c5-55a826ef51ae.png)

**Comment by ChinaMars521** [comment]
![image](https://user-images.githubusercontent.com/76717950/145774538-f35f232c-418d-4b89-acaa-b2215850e80d.png)

**Comment by ChinaMars521** [comment]
扫完无效

**Comment by Cloud370** [comment]
最好发一下版本号
如果确定是最新版了
可以先删除`data`目录下要对应的QQ号为名的文件夹
重新登录 二维码登录失效很正常 失效就再调用登录一次就行

**Comment by Cloud370** [comment]
> ![image](https://user-images.githubusercontent.com/76717950/145774510-dfdd2472-038d-4c43-83c5-55a826ef51ae.png)

你这个最好是打开文件扫吧

**Comment by ChinaMars521** [comment]
删除登录无效

**Comment by ChinaMars521** [comment]
iocq 1.21.3

**Comment by ChinaMars521** [comment]
![image](https://user-images.githubusercontent.com/76717950/145774937-0d5134d3-7e3a-4ca7-a79a-0091f03cae6c.png)

**Comment by ChinaMars521** [comment]
就是扫码登录无效了

**Comment by ChinaMars521** [comment]
而且扫码提示手表登录

**Comment by ChinaMars521** [comment]
![image](https://user-images.githubusercontent.com/76717950/145775210-0bd93580-8c7a-466e-a2f6-445a3b229a3e.png)
设置是android 协议

**Comment by ChinaMars521** [comment]
还有设置的是账号密码登录

**Comment by ChinaMars521** [comment]
更换账号效果一样，在常用电脑登录

**Comment by ChinaMars521** [comment]
以解决。

**Comment by febobo** [comment]
> 更换账号效果一样，在常用电脑登录

扫码无效最后是怎么解决的？
