### ISSUE TITLE
绑定不了设备

### ISSUE THREAD

**Issue by qinjianwei** [takayama-lily/oicq#267]
### Node.js Version

v14.18.1

### Package Version

2.1.8

### Login Protocol

Android

### Bug Description

同样的账号，同样的ip，模拟器滑块过后会出现设备保护，协议提示  “[安全提醒]当前登录存在安全风险，请使用常用设备或通过手机号登录。”

**Comment by ChinaMars521** [comment]
风控了，养号需要把

**Comment by qinjianwei** [comment]
> 风控了，养号需要把

可是模拟器和手机可以

**Comment by takayama-lily** [comment]
https://github.com/takayama-lily/oicq/wiki/01.%E4%BD%BF%E7%94%A8%E5%AF%86%E7%A0%81%E7%99%BB%E5%BD%95-(%E6%BB%91%E5%8A%A8%E9%AA%8C%E8%AF%81%E7%A0%81%E6%95%99%E7%A8%8B)
