### ISSUE TITLE
使用 pkg 打包成 exe 后运行，提示 Cannot mkdir in a snapshot. Try mountpoints instead.

### ISSUE THREAD

**Issue by leoskey** [takayama-lily/oicq#274]
我查询到 pkg 魔改了 node 的 fs API，导致 __dirname 这类会指向虚拟目录
具体列表: [https://github.com/vercel/pkg#snapshot-filesystem](https://github.com/vercel/pkg#snapshot-filesystem)
根据表格提示应使用 process.cwd() 获取目录，所以可否将 path.join(process.cwd(), "data") 作为  data_dir 默认配置？
https://github.com/takayama-lily/oicq/blob/2eb8fa2cb652d9b8e7582b6114cf72b30d87b0ab/lib/client.ts#L124

**Comment by Cloud370** [comment]
不能说魔改吧 只能说是pkg特性
如果想用pkg`config`传入自定义`data_dir`路径即可另外
```javascript
if (process.pkg) {
  Path = path.resolve(process.execPath + '/..');
} else {
  Path = path.join(require.main ? require.main.path : process.cwd())
}
```
可以这样动态获取路径.

**Comment by leoskey** [comment]
是的，在构造函数中指定 data_dir 来解决这个问题。我的愚见是默认的 require.main.path 可能会导致部分环境下无法运行，可使用 process.cwd 作为默认配置

**Comment by takayama-lily** [comment]
> 是的，在构造函数中指定 data_dir 来解决这个问题。我的愚见是默认的 require.main.path 可能会导致部分环境下无法运行，可使用 process.cwd 作为默认配置

不可。`process.cwd()`返回的是当前工作目录，而非主模块所在的目录。

**Comment by smile199705** [comment]
你们怎么操作的呀

**Comment by Cloud370** [comment]
> "Cannot mkdir in a snapshot" 错误通常是由文件系统权限不足或磁盘空间不足等原因造成的， 当然我用了pkg . --target node14-linux-x64 --o ./dist/ --no-tmpdir --snapshot=false这种格式，禁用了快照机制。但还是不行，还是去报错

传入自定义的data_dir路径即可

**Comment by smile199705** [comment]
我不清楚，这个跟路径的关系，作为内网开发，"Cannot mkdir in a snapshot" 错误通常是由文件系统权限不足或磁盘空间不足等原因造成的，而不是您的代码中访问磁盘的问题。
1、然后我的方法是禁用快照机制，添加“--no-tmpdir”， 以避免创建快照时出现权限问题，但是没有解决问题。
2、将快照机制替换为挂载点。如果您的文件系统不支持快照机制或者您无法使用快照机制，就尝试将其替换为挂载点（mountpoints），从而避免出现权限问题。您可以在项目根目录下创建名为 `.npmrc` 的文件：
```
tmp=/path/
snapshot=false
```
tmp在没网络的情况下我指定挂载的路径就是我的node_modeules路径，然后再进行pkg打包尝试（这个我还没来得急测试呢，具体）

**Comment by smile199705** [comment]
由于一个不用的，且会创建文件的模块存在导致不成功， 卸载就解决了
