### ISSUE TITLE
控制台二维码太大了，能不能给个配置参数？

### ISSUE THREAD

**Issue by SunSeekerX** [takayama-lily/oicq#276]
### Bug Description

控制台二维码太大了，能不能给个配置参数？

**Comment by takayama-lily** [comment]
什么情况下太大了？在什么设备上？

**Comment by SunSeekerX** [comment]
![image](https://user-images.githubusercontent.com/48562733/148062229-b9397376-4a1f-4097-990a-af50ef3eca9c.png)

像这样哦，很大

**Comment by SunSeekerX** [comment]
![image](https://user-images.githubusercontent.com/48562733/148062467-e8225303-ea77-4ccc-a2fa-e90554d7523a.png)

像这样很大

**Comment by TheSnowfield** [comment]
> ![image](https://user-images.githubusercontent.com/48562733/148062467-e8225303-ea77-4ccc-a2fa-e90554d7523a.png)
> 
> 像这样很大

此問題正在積極解決中.

**Comment by TheSnowfield** [comment]
f583b7bf13582f446f94eb55cbd330acba1318fb
