### ISSUE TITLE
getForwardMsg 返回3打头的10位qq号时溢出成了负数

### ISSUE THREAD

**Issue by SalimTerryLi** [takayama-lily/oicq#281]
### Node.js Version

v16.13.1

### Package Version

2.1.8

### Login Protocol

Android

### Bug Description

使用群对象的`getMemberMap()`得到的某位群老哥的qq号是正常的3开头的十位qq，但将他的消息合并转发后，再使用`getForwardMsg()`获取到的消息对象的`user_id`变成了一个负数。取负数的绝对值和他原qq号相加刚好是2^32，看起来像是int32溢出了

**Comment by takayama-lily** [comment]
临时解决方案：无符号右移
`user_id>>>0`
