### ISSUE TITLE
会考虑支持讨论组的消息吗？

### ISSUE THREAD

**Issue by dzcpy** [takayama-lily/oicq#29]
如题
之前cq-http是支持的

**Comment by takayama-lily** [comment]
不确定

**Comment by takayama-lily** [comment]
目前该仓库的使用者较少，暂时不考虑做这些本来就小众的功能吧，毕竟做起来也不简单。
未来如果使用的人多的话，可以考虑支持一下。

**Comment by takayama-lily** [comment]
目前已支持讨论组消息收发。
其他进一步的操作(获取成员列表等)暂无。

**Comment by dzcpy** [comment]
@takayama-lily 感谢

**Comment by takayama-lily** [comment]
no plan to add more features about discuss-group
