### ISSUE TITLE
bash: oicq: command not found

### ISSUE THREAD

**Issue by 56025192** [takayama-lily/oicq#293]
### Node.js Version

v16.13.2

### Package Version

npm

### Login Protocol

iPad

### Bug Description

bash: oicq: command not found
提示这个怎么解决啊

### Log Details

[root@VM-4-14-centos ~]# npm i -g oicq

added 29 packages in 775ms
[root@VM-4-14-centos ~]# oicq *************
bash: oicq: command not found

**Comment by takayama-lily** [comment]
1版本才支持全局安装
`npm i -g oicq@1`
