### ISSUE TITLE
为什么扫描和密码登录都没有反应

### ISSUE THREAD

**Issue by walirt** [takayama-lily/oicq#317]
### Node.js Version

v16.14.0

### Package(oicq) Version

latest

### Login Protocol

Watch

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

扫码登录后手机显示手表登录 确认登录后控制台没有反应
密码登录后输入ticket也没有反应

**Comment by HshousHe** [comment]
控制台回车看看呢 我刚刚试了一些是没有问题的

**Comment by HshousHe** [comment]
登录成功之后会生成一个data文件用来存你登录信息的

**Comment by takayama-lily** [comment]
默认不轮询，但是有轮询API
若需要可自行轮询

**Comment by NavinChen** [comment]
我也一样，没有反应，输入ticket回车没用
