### ISSUE TITLE
我发现调用戳一戳这个方法，会发送很多个戳一戳给对方

### ISSUE THREAD

**Issue by left0ver** [takayama-lily/oicq#326]
### Node.js Version

14.17.5

### Package(oicq) Version

lastest

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![image](https://user-images.githubusercontent.com/89240290/158833961-8fb5ea65-959a-4138-a0ec-28d4e5a49ee7.png)
![Uploading 1245742051582944BB4CD779B81C3D07.jpg…]()

### Log Details (控制台日志，请提供包含前后一段时间内的)

![image](https://user-images.githubusercontent.com/89240290/158833999-56651907-46cf-4b7f-97a4-253b19c3dc5c.png)

**Comment by dcyuki** [comment]
因为你没有对事件做判断，只要是触发了戳一戳都会跑去戳别人，机器人主动触发也算，死循环了  
![-18e67edebe6272fb.jpg](https://user-images.githubusercontent.com/37479458/159107570-fa44cf11-120e-4de1-842f-31f65208283c.jpg)

**Comment by dcyuki** [comment]
因为你没有对事件做判断，机器人戳别人也会触发事件，死循环了

![2fa14f28e3ffae88.jpg](https://user-images.githubusercontent.com/37479458/159107806-e1c8afbc-1ba3-4982-b09d-5bd3393318a8.jpg)
