### ISSUE TITLE
怎么发送艾特全体成员的消息

### ISSUE THREAD

**Issue by left0ver** [takayama-lily/oicq#333]
### Node.js Version

14.17.5

### Package(oicq) Version

lastest

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

我想让机器人自动地发送艾特全体成员的消息，我尝试使用segment来创建一个at全体消息 segment.at("all","hhh") ，并发送，但是并没有效果，有没有人能帮助我
group.getAtAllRemainder().then(res=>{
    console.log(res);
    group.sendMsg(segment.at("all","hhh"))
})

**Comment by takayama-lily** [comment]
提供一下日志

**Comment by left0ver** [comment]
![4CXZS5D)F6} YE$2KSB7})3](https://user-images.githubusercontent.com/89240290/161690086-1bfebb98-a821-4cc8-bc02-5ed5d8563c6d.png)
![YZH~$ E}S0W7BA)CU3SF%UF](https://user-images.githubusercontent.com/89240290/161690105-19b0c313-33ac-48b0-8845-e67fe83eaedd.png)

**Comment by left0ver** [comment]
> 提供一下日志

![YZH~$ E}S0W7BA)CU3SF%UF](https://user-images.githubusercontent.com/89240290/161690155-73486631-c4fb-4112-8afa-2dd22604cb76.png)
![4CXZS5D)F6} YE$2KSB7})3](https://user-images.githubusercontent.com/89240290/161690181-e13b29ee-1778-450b-9762-a9a40b51bef2.png)

**Comment by takayama-lily** [comment]
最新版本segment.at@全体成员存在bug
修复之前可使用`{type:"at",qq:"all"}`

**Comment by left0ver** [comment]
好像又有bug了，我使用你说的那种方法，加了text属性，但是只有@全体成员，并发送不了实际的内容
![G1MCUT2I)Z8P$8P}_`SK9O](https://user-images.githubusercontent.com/89240290/161873130-2c1b0cfd-614b-4fbe-9e8a-532baed0eb6a.png)
![Q@FBO`G9@`0Y9{5@V1Z%B$3](https://user-images.githubusercontent.com/89240290/161873252-a2cd6ff5-a228-46c0-b7ae-419143cd6753.png)

**Comment by left0ver** [comment]
![PTK_`SK UZQNJ496JQRH}S2](https://user-images.githubusercontent.com/89240290/161873363-0091d2cb-f03a-422f-997d-6716f94f404d.png)
