### ISSUE TITLE
关于 http api 的 get_chat_history 接口的问题

### ISSUE THREAD

**Issue by Stapxs** [takayama-lily/oicq#334]
get_chat_history 需要提供 message_id 来获取以上的消息
但是 …… 在我首次想获取历史消息的时候，并不知道最新的一条历史消息的 id
该怎么获取呢 emmm

PS：只能通过 ws 和 http api 服务

**Comment by takayama-lily** [comment]
https://github.com/takayama-lily/oicq/blob/4aef20108d428e4f6c02a3c3e38a8ab6d3768494/index.d.ts#L950-L958

**Comment by Stapxs** [comment]
ohhhhhhh
3ks
