### ISSUE TITLE
汇报客户端奇怪的行为

### ISSUE THREAD

**Issue by axon-oicq** [takayama-lily/oicq#336]
协议：安卓手表
版本：oicq@2.2.1

1. 群聊消息和私聊消息控制台均没有记录，回调也未被执行。
（可以发私聊消息给自己，但同样不能收到）

2. 群聊消息可以发送但显示如下错误（消息实际上已经被发出）：

ApiRejection { code: -80, message: '群消息发送失败，请检查消息内容' }

3. 在用手机登录对应帐号以后，显示存在风险需要修改密码。但修改后问题依旧

**Comment by takayama-lily** [comment]
1,2可能是网络不稳定

**Comment by axon-oicq** [comment]
尝试过多次，还是同样的结果。启用 TRACE 级别以后，在加载完好友、群、陌生人以后就没有后续日志了

**Comment by takayama-lily** [comment]
无法重现问题，建议提供更详细的日志等信息

**Comment by axon-oicq** [comment]
TRACE 级别下都没有足够的日志，还可以提供什么信息？

**Comment by takayama-lily** [comment]
建议自行跟踪调试

**Comment by axon-oicq** [comment]
错误地调用 removeAllListeners 导致了问题
