### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by fves1997** [takayama-lily/oicq#338]
### Node.js Version

v16.14.0

### Package(oicq) Version

2.2.1

### Login Protocol

iPad

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

1，扫码登录，手机确认后，提示登录失败，一直尝试都是这样。
[登录失败]请你稍后重试。(0x30)
![image](https://user-images.githubusercontent.com/26202838/162356935-c74b9d8b-f92d-49f5-b22e-f8a4f02b3cd9.png)
2，使用密码登录，会出现扫码验证，但是一直不出二维码。
![image](https://user-images.githubusercontent.com/26202838/162357062-3993ee2e-c254-4ca8-b0ee-1d8c25c92151.png)

尝试关闭设备认证，后使用扫码或者密码 都无法登录。

**Comment by Baytars** [comment]
大号登录没有问题，小号登录就会这样。是不是腾讯对于能够使用机器人的Q号有发消息的最低数量、好友最低数量、入群最低数量、发动态最低数量等要求？

**Comment by fves1997** [comment]
> 

就是大号，小号扫码登录几个小时后，换密码登录验证下设备就ok了，大号就是死活登不上去

**Comment by fves1997** [comment]
> > 
> 
> 就是大号，小号扫码登录几个小时后，换密码登录验证下设备就ok了，大号就是死活登不上去

出现设备验证地址，设备验证地址中的二维码无法展示时，这个时候发送SMS短信，使用验证码登录即可登录成功。
