### ISSUE TITLE
有没有办法删除监听？因为监听在Client

### ISSUE THREAD

**Issue by PluginsKers** [takayama-lily/oicq#343]
### Node.js Version

latest

### Package(oicq) Version

latest

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

```ts
let _ctx: any = client.on("message", _data => {
    _ctx = null;
});

// 希望添加一个删除监听的方法
```

**Comment by dcyuki** [comment]
oicq 的事件是基于 events 实现的，Client 本身就继承了 EventEmitter ，你完全可以使用 this.off 或者 this.removeAllListeners 来移除监听器，有不懂的可以[查看 node api](https://www.runoob.com/nodejs/nodejs-event.html)，此 issue 与协议库本身无关
