### ISSUE TITLE
windows 扫码登录可以进入 ubuntu 扫码一直显示 扫码失败，已失效或存在异常

### ISSUE THREAD

**Issue by 15844229646** [takayama-lily/oicq#348]
### Node.js Version

14.16

### Package(oicq) Version

2

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

windows 扫码登录可以进入 ubuntu 扫码一直显示 扫码失败，已失效或存在异常

![image](https://user-images.githubusercontent.com/28586982/165465852-35d174d4-2fb8-4411-a3c5-23b0dbba78b2.png)

**Comment by 15844229646** [comment]
用密码登录的话 扫码之后 显示不支持扫码登录

**Comment by 2233466866** [comment]
密码登录和扫码登录二选一，不要都开启，我是这样解决的。

**Comment by 15844229646** [comment]
我找到问题了，居然是tim的问题。tim最新版扫码，提示错误，最新版的qq就可以扫码成功。

**Comment by FakeEnd** [comment]
一样的问题，无语了，好像是版本低的问题
