### ISSUE TITLE
token过期 自动删.oicq目录的token文件

### ISSUE THREAD

**Issue by xiaofeng1998025** [takayama-lily/oicq#359]
### Node.js Version

node14.5

### Package(oicq) Version

npm

### Login Protocol

Watch

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

运行几小时token过期就掉了  .oicq配置文件目录下token也被自动删了

### Log Details (控制台日志，请提供包含前后一段时间内的)

^[[90m[2022-05-19T02:50:55.518] [MARK] [Watch:1584***269] - ^[[39m登录token过期
^[[90m[2022-05-19T02:50:55.519] [MARK] [Watch:1584***269] - ^[[39m3秒后重新连接
^[[90m[2022-05-19T02:50:58.969] [MARK] [Watch:1584***269] - ^[[39m登录token过期
^[[35m[2022-05-19T02:50:58.970] [FATAL] [Watch:1584***269] - ^[[39mENOENT: no such file or directory, unlink '/root/.oicq/1584***269/token'
^[[91m[2022-05-19T03:05:59.028] [ERROR] [Watch:1584***269] - ^[[39mread ECONNRESET
^[[90m[2022-05-19T03:05:59.032] [MARK] [Watch:1584***269] - ^[[39m60.29.238.126:8080 closed
^[[91m[2022-05-19T07:02:09.423] [ERROR] [Watch:1584***269] - ^[[39m反向ws连接(ws://127.0.0.1***/qq/receive)被关闭，关闭码1006，将在3000毫秒后尝试连接。

**Comment by takayama-lily** [comment]
更新到最新版本2.2.3

**Comment by xiaofeng1998025** [comment]
又掉了 这是什么原因 有交流群或者讨论组么 版本我升级到了2.2.3了

^[[91m[2022-05-19T13:44:03.424] [ERROR] [Watch:158***6269] - ^[[39mfailed to send: [Private: 179***1742] 发
送失败，请先添加对方为好友(16)
^[[91m[2022-05-19T14:35:45.353] [ERROR] [Watch:158***6269] - ^[[39mfailed to send: [Private: 289***9707] 发
送失败，请先添加对方为好友(16)
^[[91m[2022-05-19T14:35:45.495] [ERROR] [Watch:158***6269] - ^[[39mfailed to send: [Private: 289***9707] 发
送失败，请先添加对方为好友(16)
^[[91m[2022-05-19T14:36:54.692] [ERROR] [Watch:158***6269] - ^[[39mfailed to send: [Private: 289***9707] 发
送失败，请先添加对方为好友(16)
^[[91m[2022-05-19T14:37:49.559] [ERROR] [Watch:158***6269] - ^[[39mfailed to send: [Private: 289***9707] 发
送失败，请先添加对方为好友(16)
^[[90m[2022-05-19T15:30:44.228] [MARK] [Watch:158***6269] - ^[[39m111.206.99.90:8080 closed

**Comment by xiaofeng1998025** [comment]
> 又掉了 这是什么原因 有交流群或者讨论组么 版本我升级到了2.2.3了
> 
> ^[[91m[2022-05-19T13:44:03.424] [ERROR] [Watch:158_**6269] - ^[[39mfailed to send: [Private: 179**_1742] 发 送失败，请先添加对方为好友(16) ^[[91m[2022-05-19T14:35:45.353] [ERROR] [Watch:158_**6269] - ^[[39mfailed to send: [Private: 289**_9707] 发 送失败，请先添加对方为好友(16) ^[[91m[2022-05-19T14:35:45.495] [ERROR] [Watch:158_**6269] - ^[[39mfailed to send: [Private: 289**_9707] 发 送失败，请先添加对方为好友(16) ^[[91m[2022-05-19T14:36:54.692] [ERROR] [Watch:158_**6269] - ^[[39mfailed to send: [Private: 289**_9707] 发 送失败，请先添加对方为好友(16) ^[[91m[2022-05-19T14:37:49.559] [ERROR] [Watch:158_**6269] - ^[[39mfailed to send: [Private: 289**_9707] 发 送失败，请先添加对方为好友(16) ^[[90m[2022-05-19T15:30:44.228] [MARK] [Watch:158***6269] - ^[[39m111.206.99.90:8080 closed

找到原因了 qq冻结了
