### ISSUE TITLE
升级3.2.2群私聊消息是不是改了 现在回复都是先加好友

### ISSUE THREAD

**Issue by xiaofeng1998025** [takayama-lily/oicq#360]
### Node.js Version

16.15.0

### Package(oicq) Version

3.2.2

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

3.2.2是不是该了消息方式的，群私聊回复现在提示要加好好友，还有请教怎么设置群发送匿名消息，还有大佬有没有交流群啊

### Log Details (控制台日志，请提供包含前后一段时间内的)

0|index 15 | [2022-05-20T07:02:09.491] [ERROR] [Watch:158***6269] - failed to send: [Private: 179***1742] 发送失败，请先添加对方为好友(16)
0|index 15 | [2022-05-20T07:02:13.149] [ERROR] [Watch:158***6269] - failed to send: [Private: 123***37] 发送失败，请先添加对方为好友(16)
0|index 15 | [2022-05-20T07:02:14.354] [ERROR] [Watch:158***6269] - failed to send: [Private: 164***319] 发送失败，请先添加对方为好友(16)
0|index 15 | [2022-05-20T07:21:16.055] [ERROR] [Watch:158***6269] - failed to send: [Private: 489***409] 发送失败，请先添加对方为好友(16)

**Comment by takayama-lily** [comment]
临时会话有单独api
