### ISSUE TITLE
支持onebot标准

### ISSUE THREAD

**Issue by Brx86** [takayama-lily/oicq#363]
### Node.js Version

v18.2.0

### Package(oicq) Version

latest

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

[支持onebot标准的版本](https://github.com/takayama-lily/oicq/tree/master/http-api)已经很久没更新了，是否可以基于最新的oicq版本提供onebot标准的api？

**Comment by takayama-lily** [comment]
onebot11的版本不会再更新了，onebot12目前没有开发计划。
