### ISSUE TITLE
一个不起眼的提议

### ISSUE THREAD

**Issue by jfictory** [takayama-lily/oicq#370]
### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

作者大大可以可以考虑做一个定时任务功能，可以用于刷火花，每日推送天气这样子

**Comment by dmlgzs** [comment]
~~这个可以自己写吧~~

**Comment by dcyuki** [comment]
oicq 只是一个协议库，本身不包含也不应该包含除协议本身的其它功能，想要有定时任务可以看下 [node-schedule](https://github.com/node-schedule/node-schedule) 实现一个
