### ISSUE TITLE
关于大量发送图片后"群消息可能被风控，将尝试使用分片发送",无法追踪错误来源(萌新)

### ISSUE THREAD

**Issue by ahhhs** [takayama-lily/oicq#384]
### Node.js Version

14.0

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![image](https://user-images.githubusercontent.com/78841286/177564385-933b6958-87c7-40dd-89a1-5a611f35fef1.png)
想请教一下,当发送大量图片,被风控以后,会输出日志"群消息可能被风控，将尝试使用分片发送"; 随后我通过日志在该位置输入测试日志,
![image](https://user-images.githubusercontent.com/78841286/177564892-f92e67f2-1812-475a-9001-7c4fda0e984a.png)
但是发现测试日志没有打印出来; 紧接着我将"群消息可能被风控，将尝试使用分片发送"更改成其他的字符串; 运行后还是会输出"群消息可能被风控，将尝试使用分片发送";但是我全局搜索后,已经没有该日志了;无效
![image](https://user-images.githubusercontent.com/78841286/177565311-f02fa79b-3145-4b91-b767-4c2c70b4b84e.png)
想咨询一下是怎么回事,应该怎么追踪来源

**Comment by ahhhs** [comment]
![image](https://user-images.githubusercontent.com/78841286/177683065-637e4296-051b-4a40-956e-75f453a76c0b.png)
zha找到来源了,但是找不到解决的办法,  报错信息:
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason

**Comment by takayama-lily** [comment]
with .catch()
