### ISSUE TITLE
关于文本消息无法和图片一起发送的问题

### ISSUE THREAD

**Issue by jfictory** [takayama-lily/oicq#388]
### Node.js Version

16.16.0

### Package(oicq) Version

latest

### Login Protocol

iPad

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

我想要让图片和文本消息合在一起发送，但是似乎这样不行，是不支持吗？

### Log Details (控制台日志，请提供包含前后一段时间内的)

![image](https://user-images.githubusercontent.com/86643414/179811605-82fba506-409e-4e54-858f-dfe6113b7ca7.png)

**Comment by jyiL** [comment]
```javascript
msg.reply([
  segment.image("https://sqimg.qq.com/qq_product_operations/im/qqlogo/imlogo.png"),
  "hello"
])
```

**Comment by jfictory** [comment]
> ```js
> msg.reply([
>   segment.image("https://sqimg.qq.com/qq_product_operations/im/qqlogo/imlogo.png"),
>   "hello"
> ])
> ```

谢谢大佬
