### ISSUE TITLE
无法获取群员对象

### ISSUE THREAD

**Issue by MCBW666** [takayama-lily/oicq#392]
### Node.js Version

16.14.2

### Package(oicq) Version

2.x

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![QQ图片20220723202437](https://user-images.githubusercontent.com/102389677/180604847-d3a9960a-ffbf-4590-bf34-dce9efd2551a.png)
![QQ图片20220723202503](https://user-images.githubusercontent.com/102389677/180604852-5b09c5fa-16bf-4c58-b938-9bd4939cfb8d.png)
如图 所以为什么？

### Log Details (控制台日志，请提供包含前后一段时间内的)

Error: 群973105927中找不到群员89442586
这是我设为严格模式获取后的报错

**Comment by MCBW666** [comment]
。

**Comment by takayama-lily** [comment]
因为还没有加载群员列表，你可以手动加载一下，或者不要使用strict模式
