### ISSUE TITLE
发消息的顺序比较玄学

### ISSUE THREAD

**Issue by luanmenglei** [takayama-lily/oicq#393]
### Node.js Version

v16.14.2

### Package(oicq) Version

latest

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![image](https://user-images.githubusercontent.com/52412246/180767668-c4a065ac-3318-4898-b9b9-d28a05e859ba.png)
![I_1@LQ`$K9X$(X)1@_VR)@6](https://user-images.githubusercontent.com/52412246/180767750-b66ed0cd-554a-4017-a040-c3549e7a5aba.png)
![image](https://user-images.githubusercontent.com/52412246/180767775-37aca17c-6d46-4054-9574-2fc6b1b62a38.png)
如上三图，我代码写的发消息顺序是abc，但有的时候是abc，有的时候是bac，有的时候是cab....
不知道这是我写法问题还是别的问题

### Log Details (控制台日志，请提供包含前后一段时间内的)

控制台的日志和qq接收到的消息的顺序是一样的

**Comment by MCBW666** [comment]
这个就是这样的 送达时间不同 因为返回的是promise 所以你懂的 你可以在发送函数返回的promise发送下一条 保证顺序 当然这样可能就复杂了

**Comment by dcyuki** [comment]
你说有没有一种可能，sendMsg 是 promise 异步函数

**Comment by luanmenglei** [comment]
okok，看源码的时候也看到了
