### ISSUE TITLE
当前QQ版本过低，请升至最新版登陆。点击进入下载页面

### ISSUE THREAD

**Issue by liuqianpan2008** [takayama-lily/oicq#395]
### Node.js Version

v16.15.0

### Package(oicq) Version

2.3.1

### Login Protocol

iPad

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

<img width="937" alt="C9D38C0A2DC3E5007D50511E19D69ED0" src="https://user-images.githubusercontent.com/80571808/181521614-81b63d14-dbf6-4d99-b3ec-9ac4667016ee.png">

### Log Details (控制台日志，请提供包含前后一段时间内的)

<img width="937" alt="C9D38C0A2DC3E5007D50511E19D69ED0" src="https://user-images.githubusercontent.com/80571808/181521614-81b63d14-dbf6-4d99-b3ec-9ac4667016ee.png">

**Comment by takayama-lily** [comment]
duplicate #369
