### ISSUE TITLE
如何获取撤回消息的内容，想做一个不允许群员撤回消息的功能

### ISSUE THREAD

**Issue by cyf-maple** [takayama-lily/oicq#399]
### Node.js Version

v16.16.0

### Package(oicq) Version

latest

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![H3`WG8UCOBE{9BGH6WIK0ZO](https://user-images.githubusercontent.com/41290011/183242300-1e06848a-a571-4895-867e-841e5d14577d.png)

### Log Details (控制台日志，请提供包含前后一段时间内的)

控制台日志如上，撤回了那个{face:306}消息，通过message_id无法获取消息，不知道是不是我的写法有问题，没写过nodejs

**Comment by takayama-lily** [comment]
撤回后服务器上就没了，所以无法获取

**Comment by cyf-maple** [comment]
> 撤回后服务器上就没了，所以无法获取

🆗，我用redis做2分钟内暂存实现这个功能了，message_id太好用了，直接可以当key
