### ISSUE TITLE
request.group.add中可以获取是扫描二维码进群还是通过群号搜索进群的吗

### ISSUE THREAD

**Issue by cyf-maple** [takayama-lily/oicq#414]
### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![image](https://user-images.githubusercontent.com/41290011/186349250-c9ca0a80-a64d-4741-9849-c519095d1ee7.png)
如图，不知道哪个是的

**Comment by takayama-lily** [comment]
bukeyi
