### ISSUE TITLE
如何隐藏oicq自带的输出

### ISSUE THREAD

**Issue by suno2015** [takayama-lily/oicq#419]
### Node.js Version

v16.17.0

### Package(oicq) Version

latest

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

如何将oicq本身的输出隐藏掉，因为我正在制作一个cli程序，oicq本身的输出会造成混乱

**Comment by dmlgzs** [comment]
建议多看看[文档](https://oicqjs.github.io/oicq/interfaces/Config.html#log_level)

**Comment by suno2015** [comment]
> 建议多看看[文档](https://oicqjs.github.io/oicq/interfaces/Config.html#log_level)

谢谢🙏
