### ISSUE TITLE
都用protobufjs了，考虑一下用protobufjs生成的onebot协议？

### ISSUE THREAD

**Issue by lz1998** [takayama-lily/oicq#42]
proto文件：https://github.com/protobufbot/onebot_idl

```bash
npx pbjs -t static-module -w commonjs -o proto.js  *.proto --force-long

pbts -o proto.d.ts proto.js
```

**Comment by lz1998** [comment]
顺便建议可以用TS？

**Comment by takayama-lily** [comment]
是指让http-api支持使用protobuf进行数据传输？

**Comment by lz1998** [comment]
> 是指让http-api支持使用protobuf进行数据传输？

用 json 和 protobuf 都可以，可以都支持一下，主要是生成的强类型的协议定义（TypeScript），可能会更不容易出错，并且如果使用proto，更方便与http/websocket的另一端进行同步

**Comment by takayama-lily** [comment]
用protobuf来约束其实是个好办法。
就是不知道一般用户对此的接受程度如何。
未来可以考虑同时支持吧。

**Comment by dzcpy** [comment]
TS +1

**Comment by AsakuraMizu** [comment]
TS +2

**Comment by yuyiRai** [comment]
TS+10086

**Comment by takayama-lily** [comment]
.proto已经被我扬了。onebot搞pb好像也没啥意思。
另外ts目前只提供d.ts文件，内部实现暂时不会考虑用、
