### ISSUE TITLE
无法编译: `Module parse failed: Unexpected token`

### ISSUE THREAD

**Issue by WindLeaf233** [takayama-lily/oicq#424]
### Node.js Version

v14.15.0

### Package(oicq) Version

latest

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![image](https://user-images.githubusercontent.com/58383985/188303195-75926c42-efba-4f5f-ab41-7baaac7ba030.png)

### Log Details (控制台日志，请提供包含前后一段时间内的)

除了上面的截图, 无日志提供.
其他都是 `npm i` 和 `npm audit fix` 的日志.

**Comment by goodspeed34** [comment]
升级 NodeJS 版本，看看 v16 是不是能跑

**Comment by WindLeaf233** [comment]
> 升级 NodeJS 版本，看看 v16 是不是能跑

很抱歉, 我的系统版本不支持升级 `node v16`, 我看到仓库 `README.md` 写道 ***最低支持的 Node 版本是 v14***.

**Comment by goodspeed34** [comment]
> > 升级 NodeJS 版本，看看 v16 是不是能跑
> 
> 很抱歉, 我的系统版本不支持升级 `node v16`, 我看到仓库 `README.md` 写道 _**最低支持的 Node 版本是 v14**_.

那个大概是不对的 😕

**Comment by WindLeaf233** [comment]
> > > 升级 NodeJS 版本，看看 v16 是不是能跑
> > 
> > 
> > 很抱歉, 我的系统版本不支持升级 `node v16`, 我看到仓库 `README.md` 写道 _**最低支持的 Node 版本是 v14**_.
> 
> 那个大概是不对的 confused

这就很迷惑了 :disappointed:... 那请问还有什么别的解决办法吗?

**Comment by goodspeed34** [comment]
> > > > 升级 NodeJS 版本，看看 v16 是不是能跑
> > > 
> > > 
> > > 很抱歉, 我的系统版本不支持升级 `node v16`, 我看到仓库 `README.md` 写道 _**最低支持的 Node 版本是 v14**_.
> > 
> > 
> > 那个大概是不对的 confused
> 
> 这就很迷惑了 😞... 那请问还有什么别的解决办法吗?

可能是跟 ts 配置有关的 bug，现在的解决办法是从 nodejs 官方安装 node v16 或者用一个叫 `n` 的包一键安装。

我明天看看能不能让它重新在 node v14 上跑起来。

https://www.npmjs.com/package/n

**Comment by WindLeaf233** [comment]
> > > > > 升级 NodeJS 版本，看看 v16 是不是能跑
> > > > 
> > > > 
> > > > 很抱歉, 我的系统版本不支持升级 `node v16`, 我看到仓库 `README.md` 写道 _**最低支持的 Node 版本是 v14**_.
> > > 
> > > 
> > > 那个大概是不对的 confused
> > 
> > 
> > 这就很迷惑了 disappointed... 那请问还有什么别的解决办法吗?
> 
> 可能是跟 ts 配置有关的 bug，现在的解决办法是从 nodejs 官方安装 node v16 或者用一个叫 `n` 的包一键安装。
> 
> 我明天看看能不能让它重新在 node v14 上跑起来。
> 
> [npmjs.com/package/n](https://www.npmjs.com/package/n)

我是 `Windows7`, 而 [n](https://www.npmjs.com/package/n) 不支持 `win32` 平台 :disappointed:

**Comment by WindLeaf233** [comment]
已解决, 在排查了一段时间后发现和 `oicq` 和 `typescript` 没有关系, 而是 `webpack` 的相关问题.

在对 `webpack.config.js` 进行设置后解决了, 感谢 @goodspeed34 的回复!
