### ISSUE TITLE
测试了俩个小孩提示了风险登录，并不是设备锁

### ISSUE THREAD

**Issue by Yzwcp** [takayama-lily/oicq#431]
### Node.js Version

node-16

### Package(oicq) Version

latest

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

![BC}H 03)}HX{R06E0R K9AK](https://user-images.githubusercontent.com/59905716/189837455-12fe01fa-9210-47ee-88fa-057f294cb2d0.png)

**Comment by Yzwcp** [comment]
system.login.device 也监听不到这个风险

**Comment by dcyuki** [comment]
这是 error，并不是登录授权校验

**Comment by Yzwcp** [comment]
> 

换了登录协议已解决

**Comment by AdminHcat** [comment]
> > 
> 
> 换了登录协议已解决

请Close
