### ISSUE TITLE
at 全体成员时发送不了消息，单纯at了全体成员

### ISSUE THREAD

**Issue by left0ver** [takayama-lily/oicq#439]
### Node.js Version

16.17.0

### Package(oicq) Version

2.3.1.  installed by yarn

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

<img width="686" alt="image" src="https://user-images.githubusercontent.com/89240290/190427327-35664afd-a1eb-43ca-a64c-19f31f573c7c.png">
<img width="839" alt="image" src="https://user-images.githubusercontent.com/89240290/190427524-8bdc18a3-d499-4a1f-99b1-fdfa064244ad.png">

尝试了多种发消息的方式，都是如此（可以at 全体，但是发不出去消息）

### Log Details (控制台日志，请提供包含前后一段时间内的)

<img width="860" alt="image" src="https://user-images.githubusercontent.com/89240290/190427688-5bfec164-5885-4130-b1a2-88569ef8206d.png">

**Comment by ltxhhz** [comment]
请尝试把那段代码改成
```js
group.sendMsg([segment.at('all'),'大家好']
```

可以尝试阅读[文档](https://oicqjs.github.io/oicq/)

然后把issue关了
