### ISSUE TITLE
如何主动发送一条私聊消息

### ISSUE THREAD

**Issue by Yzwcp** [takayama-lily/oicq#443]

**Comment by koushiyu** [comment]
![image](https://user-images.githubusercontent.com/52336785/192817935-9585bd4d-bf09-4814-9752-41ac43626073.png)
![image](https://user-images.githubusercontent.com/52336785/192817989-935e3297-4d90-4287-8ed9-4b21edab674c.png)
![image](https://user-images.githubusercontent.com/52336785/192818028-86477227-feab-4643-9629-173dfa7a62e7.png)

**Comment by Yzwcp** [comment]
我看到过 但是点进去ts参数没有指定qq的参数
![8FA5@Y% GPMKBBM}%H9WFQ](https://user-images.githubusercontent.com/59905716/192822305-177c0976-b17c-4d05-871c-d635bf77f6e3.png)

**Comment by Yzwcp** [comment]
好的这个方法可以  我试试

**Comment by Yzwcp** [comment]
感谢老哥提供思路 已解决 
![R9505WG(I007RVXPRJ{EF_R](https://user-images.githubusercontent.com/59905716/192829127-26fe152d-08f5-450b-8c1f-c9ed91e67179.png)
