### ISSUE TITLE
关于新增加的导出生成消息id函数

### ISSUE THREAD

**Issue by Raymondzll** [takayama-lily/oicq#446]
### Node.js Version

14.15.0

### Package(oicq) Version

2.3.1

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

查看后好像是在\lib\message\message.js中定义，\lib\message\index.js中也能在export中正常查看，但\lib\index.js中并未像parseGroupMessageId函数一样正常导出，请问这是有意设计的还是bug？

**Comment by takayama-lily** [comment]
导出生成消息id函数有人pr了。

> 目前解决方案是
> 
> `const {genGroupMessageId}=require(“oicq\\lib\\message\\index.js”)`
> 
> 另外source（quotable）能否实现添加messageid对象？

关于这个，messageid已经deprecated了，不会添加。

**Comment by Raymondzll** [comment]
好的好的，谢谢库主回答🙏
