### ISSUE TITLE
为什么协议不直接使用更高采样率的sik而是amr？

### ISSUE THREAD

**Issue by count-bt** [takayama-lily/oicq#463]
### Node.js Version

16

### Package(oicq) Version

1.0于2.0

### Login Protocol

iPad

**Comment by goodspeed34** [comment]
> SILK编解码器拥有专利，并且SILK SDK有独立的许可协议。[[4]](https://zh.wikipedia.org/wiki/#cite_note-codec-licence-4)该编解码器是一个[开源的](https://zh.wikipedia.org/wiki/%E5%BC%80%E6%94%BE%E6%BA%90%E4%BB%A3%E7%A0%81)[免费软件](https://zh.wikipedia.org/wiki/%E5%85%8D%E8%B2%BB%E8%BB%9F%E9%AB%94)，可以有限定的[买断式授权](https://zh.wikipedia.org/wiki/%E8%B2%B7%E6%96%B7%E5%BC%8F%E6%8E%88%E6%AC%8A)用于使用和分发。[[3]](https://zh.wikipedia.org/wiki/#cite_note-website-3)[[5]](https://zh.wikipedia.org/wiki/#cite_note-h-online-5) 该 SDK最初只需要提供姓名、地址、电话和如何使用SILK的描述即可被应用程序使用。[[3]](https://zh.wikipedia.org/wiki/#cite_note-website-3)截至2012年（版本1.0.9），该SDK可以直接下载，但授权仅限于内部评估和测试目的，不包括软件分发或在任何商业产品或服务中使用。

**Comment by TheSnowfield** [comment]
> > SILK编解码器拥有专利，并且SILK SDK有独立的许可协议。[[4]](https://zh.wikipedia.org/wiki/#cite_note-codec-licence-4)该编解码器是一个[开源的](https://zh.wikipedia.org/wiki/%E5%BC%80%E6%94%BE%E6%BA%90%E4%BB%A3%E7%A0%81)[免费软件](https://zh.wikipedia.org/wiki/%E5%85%8D%E8%B2%BB%E8%BB%9F%E9%AB%94)，可以有限定的[买断式授权](https://zh.wikipedia.org/wiki/%E8%B2%B7%E6%96%B7%E5%BC%8F%E6%8E%88%E6%AC%8A)用于使用和分发。[[3]](https://zh.wikipedia.org/wiki/#cite_note-website-3)[[5]](https://zh.wikipedia.org/wiki/#cite_note-h-online-5) 该 SDK最初只需要提供姓名、地址、电话和如何使用SILK的描述即可被应用程序使用。[[3]](https://zh.wikipedia.org/wiki/#cite_note-website-3)截至2012年（版本1.0.9），该SDK可以直接下载，但授权仅限于内部评估和测试目的，不包括软件分发或在任何商业产品或服务中使用。

其實這個不是主要原因。
要問那就是沒做了， 不過我記得前段時間有做node silk綁定來著，應該是能用的才對。

**Comment by grasp-ccmo** [comment]
> > > SILK编解码器拥有专利，并且SILK SDK有独立的许可协议。[[4]](https://zh.wikipedia.org/wiki/#cite_note-codec-licence-4)该编解码器是一个[开源](https://zh.wikipedia.org/wiki/%E5%BC%80%E6%94%BE%E6%BA%90%E4%BB%A3%E7%A0%81)的[免费软件](https://zh.wikipedia.org/wiki/%E5%85%8D%E8%B2%BB%E8%BB%9F%E9%AB%94)，可以有限定的[买断式授权](https://zh.wikipedia.org/wiki/%E8%B2%B7%E6%96%B7%E5%BC%8F%E6%8E%88%E6%AC%8A)用于使用和分发。[[3](https://zh.wikipedia.org/wiki/#cite_note-website-3)][[5]](https://zh.wikipedia.org/wiki/#cite_note-h-online-5)该 SDK最初只需要提供姓名、地址、电话和如何使用SILK的描述即可被应用程序使用。[[3]](https://zh.wikipedia.org/wiki/#cite_note-website-3)截至2012年（版本1.0.9），该SDK可以直接下载，但授权仅限于内部评估和测试目的，不包括软件分发或在任何商业产品或服务中使用。
> 
> 其實這個不是主要原因。 要問那就是沒做了， 不過我記得前段時間有做node silk綁定來著，應該是能用的才對。
2.0有silk转码？
