### ISSUE TITLE
想在QQ里面发送消息时使用markdown的格式发送,有没有大佬有什么好的方法 

### ISSUE THREAD

**Issue by left0ver** [takayama-lily/oicq#487]
### Node.js Version

16.17.0

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

想在QQ里面发送消息时使用markdown的格式发送,有没有大佬有什么好的方法

**Comment by yuchiXiong** [comment]
正好在捣鼓原神机器人 [Yunzai-Bot](https://github.com/Le-niao/Yunzai-Bot)，这里有几个插件实现了 Markdown 消息发送的功能，希望对你有用

[TRSS-Plugin: Apps/Markdown.js](https://github.com/TimeRainStarSky/TRSS-Plugin/blob/main/Apps/Markdown.js)
[I-Plugin: apps/markdown.js](https://github.com/liuly0322/l-plugin/blob/main/apps/markdown.js)

思路都是通过 HTML 渲染 Markdown ，然后将 HTML 生成为图片。

**Comment by left0ver** [comment]
嗯嗯,非常感谢,这种方法发送的图片,也是一种不错的思路,我可能更想直接发送markdown的那种文本,然后自己也调研了一下,貌似确实不太可行

**Comment by yuchiXiong** [comment]
这个感觉挺困难的哎，QQ 消息现在的格式貌似也不支持排版？我记得气泡消息出来之前的版本还能设置一个整体的文本样式来着，现在气泡消息看起来把这部分都屏蔽掉了
