### ISSUE TITLE
events.js entities.js 文件里没有代码

### ISSUE THREAD

**Issue by 2-3-8-4-0-3-6-9-9-2** [takayama-lily/oicq#497]
### Node.js Version

null

### Package(oicq) Version

null

### Login Protocol

None

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

oicq-2.3\node_modules\oicq\lib 路径下， 这两个js文件没有代码
events.js    events.d.ts
entities.js   entities.d.ts

### Log Details (控制台日志，请提供包含前后一段时间内的)

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

**Comment by dcyuki** [comment]
[event.ts](https://github.com/takayama-lily/oicq/blob/main/lib/events.ts) 里本身就没有任何逻辑代码，全是 `interface`

**Comment by 2-3-8-4-0-3-6-9-9-2** [comment]
> [event.ts](https://github.com/takayama-lily/oicq/blob/main/lib/events.ts)里本身就没有任何分发代码，全部是`interface`

了解！ 我说怎么ts一大堆代码，js里啥都没有呢！

**Comment by 2-3-8-4-0-3-6-9-9-2** [comment]
问题解决，关闭。
