### ISSUE TITLE
[Must Fix] 所有设备登录所提供的版本全过期!

### ISSUE THREAD

**Issue by CreaklerFurry** [takayama-lily/oicq#503]
### Node.js Version

v19.6.0

### Package(oicq) Version

npm

### Login Protocol

Android

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

全部设备元数据已过期!

**Comment by TennisJin** [comment]
同样的问题，所有协议显示版本过期

**Comment by qianzhiyuan** [comment]
一样..

**Comment by bigqiao** [comment]
一样，但是这个还是分帐号的。有些号全部不行，有些号就还能苟活。

**Comment by chuanzhubin** [comment]
[禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。

**Comment by chuanzhubin** [comment]
[2023-02-21T14:04:23.715] [MARK] [Android:****] - 二维码图片已保存到：D:\GIT\oicq_chuan\data\****\qrcode.png
[2023-02-21T14:04:23.715] [MARK] [Android:****] - 扫码后按Enter完成登录

[2023-02-21T14:04:28.394] [ERROR] [Android:*****] - [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。

**Comment by bigqiao** [comment]
现在wach扫码登录还能用，但是登录后的token文件变成了160字节，导致重登也登不上，也要扫码。

**Comment by feiyu-web** [comment]
一样的情况, 同ip也试过了

![image](https://user-images.githubusercontent.com/76613352/221083369-ecd8bb2e-a5a5-4b4e-a5f3-ebea608a1095.png)

**Comment by Arondight** [comment]
我以前自个 patch 了一下，感觉用的还挺正常的，你可以拿去用用

https://github.com/Arondight/Adachi-BOT/blob/dev/.patches/oicq%2B2.3.1.patch

**Comment by CreaklerFurry** [comment]
> 我以前自个 patch 了一下，感觉用的还挺正常的，你可以拿去用用
> 
> https://github.com/Arondight/Adachi-BOT/blob/dev/.patches/oicq%2B2.3.1.patch

@Arondight 

but..
![image](https://user-images.githubusercontent.com/77380048/221162451-c490e1ca-c373-41f2-b15d-61a02b624cbb.png)

**Comment by cyczq11** [comment]
同样问题来问的~~~~关注了

**Comment by rotcar** [comment]
同样问题，搞了一星期了。滑动验证后没有返回消息

**Comment by Arondight** [comment]
> 我以前自个 patch 了一下，感觉用的还挺正常的，你可以拿去用用
> 
> https://github.com/Arondight/Adachi-BOT/blob/dev/.patches/oicq%2B2.3.1.patch

1. 用 ipad 协议
2. 随机化是需要的

**Comment by xiaofeiTM233** [comment]
一个小时前突然失效

**Comment by xiaofeiTM233** [comment]
![JWF}3%8U$PYG~G4Z(TG7%AO](https://user-images.githubusercontent.com/55832499/221577155-f73c8d45-f8c7-4865-8271-025e9f10b14c.png)

**Comment by CreaklerFurry** [comment]
See https://github.com/takayama-lily/oicq/issues/503#issuecomment-1446333609

**Comment by CreaklerFurry** [comment]
> 

@xiaofeiTM233 能提供一下原文章链接吗！谢谢！

**Comment by Anmours** [comment]
> ![JWF}3%8U$PYG~G4Z(TG7%AO](https://user-images.githubusercontent.com/55832499/221577155-f73c8d45-f8c7-4865-8271-025e9f10b14c.png)

0301测试无效

**Comment by bling-yshs** [comment]
> 我以前自个 patch 了一下，感觉用的还挺正常的，你可以拿去用用
> 
> https://github.com/Arondight/Adachi-BOT/blob/dev/.patches/oicq%2B2.3.1.patch

看起来不太有用
![image](https://user-images.githubusercontent.com/41812674/222291309-88ee94fd-4c3a-425f-80fa-35b112d275ad.png)

**Comment by xiaofeiTM233** [comment]
> > 
> 
> @xiaofeiTM233 能提供一下原文章链接吗！谢谢！

https://gitee.com/bling_yshs/Yunzai-v3-Installation-Steps#gitbash-%E5%86%85%E6%8A%A5%E9%94%99%E7%B1%BB

**Comment by xiaofeiTM233** [comment]
> > ![JWF}3%8U$PYG~G4Z(TG7%AO](https://user-images.githubusercontent.com/55832499/221577155-f73c8d45-f8c7-4865-8271-025e9f10b14c.png)
> 
> 0301测试无效

![image](https://user-images.githubusercontent.com/55832499/222336798-45498c6b-fb63-4d2e-8a9c-8dd782067a74.png)
已经成功的仍然可以使用，只要每次出错时把之前生成的data复制过去就行

**Comment by CreaklerFurry** [comment]
> > > ![JWF}3%8U$PYG~G4Z(TG7%AO](https://user-images.githubusercontent.com/55832499/221577155-f73c8d45-f8c7-4865-8271-025e9f10b14c.png)
> > 
> > 
> > 0301测试无效
> 
> ![image](https://user-images.githubusercontent.com/55832499/222336798-45498c6b-fb63-4d2e-8a9c-8dd782067a74.png) 已经成功的仍然可以使用，只要每次出错时把之前生成的data复制过去就行

> 使用 proxy 是否可以实现在同一个虚拟局域网内登录? (疑惑)

**Comment by xiaofeiTM233** [comment]
> > 使用 proxy 是否可以实现在同一个虚拟局域网内登录? (疑惑)

我不是这个解决方案的提供者，建议去找那个提供解决方案的人（gitee上那个）

**Comment by bling-yshs** [comment]
> > > > ![JWF}3%8U$PYG~G4Z(TG7%AO](https://user-images.githubusercontent.com/55832499/221577155-f73c8d45-f8c7-4865-8271-025e9f10b14c.png)
> > > 
> > > 
> > > 0301测试无效
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/55832499/222336798-45498c6b-fb63-4d2e-8a9c-8dd782067a74.png) 已经成功的仍然可以使用，只要每次出错时把之前生成的data复制过去就行
> 
> > 使用 proxy 是否可以实现在同一个虚拟局域网内登录? (疑惑)

可以搭建代理然后扫码，有人试过。另外这个转换项目是 https://github.com/Akegarasu/gocq-token-convert 但是不适配最新的CI版本的gocqhttp

**Comment by xiaofeiTM233** [comment]
> 可以搭建代理然后扫码，有人试过。另外这个转换项目是 https://github.com/Akegarasu/gocq-token-convert 但是不适配最新的CI版本的gocqhttp

我是之前试过这个不行才去找到那个方法的
