### ISSUE TITLE
能不能发送文件

### ISSUE THREAD

**Issue by bincooo** [takayama-lily/oicq#505]
### Node.js Version

18+

### Login Protocol

None

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

能不能发送文件，求大佬解答

**Comment by CreaklerFurry** [comment]
https://oicqjs.github.io/oicq/classes/Friend.html#sendFile ?

**Comment by bincooo** [comment]
> https://oicqjs.github.io/oicq/classes/Friend.html#sendFile ?

感谢🙏，是我眼拙了。我去试试～

**Comment by so1ve** [comment]
记得关掉issue
