### ISSUE TITLE
如何管理client.on的监听事件

### ISSUE THREAD

**Issue by Vi-brance** [takayama-lily/oicq#519]
我设置了多个`client.on`监听事件的回调函数（比如我对`system.online`设置了多个监听器），如果某一个监听器不需要监听这个事件了，该怎么移除它？
我查看了API文档，有一个`client.off`方法，但是这个方法会一次移除掉整个监听事件，这不是我想要的结果。

**Comment by lc-cn** [comment]
const listener=()=>{}

**Comment by Vi-brance** [comment]
我在翻看文档的时候没发现`off`方法能够获取两个参数，按你的写法我在文档中实现了一下：
![image](https://user-images.githubusercontent.com/82794754/235148052-1e14a4fc-c67e-4a27-9e1c-cad8c468e8f0.png)
似乎只有on方法能接受两个参数
![image](https://user-images.githubusercontent.com/82794754/235148125-4a6ce565-1f6a-4b88-98da-e958620b4cab.png)
而off只能接受一个参数
![image](https://user-images.githubusercontent.com/82794754/235148185-fb902382-9fb9-483e-88bf-be942b000ffe.png)
这里显示参数数量错误
![image](https://user-images.githubusercontent.com/82794754/235148248-5c688d56-831a-4471-803e-cce31ff1c8e6.png)

我记得`off`和`on`方法都有一个重载的方法，但那个重载方法要求第一个参数不属于`EventMap`，因此这对属于`EventMap`的事件似乎是无效的。

**Comment by dcyuki** [comment]
oicq 的事件是基于 events 实现的，Client 类继承了 EventEmitter ，有疑问可以 [查看 node api](https://nodejs.org/api/events.html#class-eventemitter)，此 issue 与协议库本身无关

**Comment by Vi-brance** [comment]
不好意思，我发现了问题所在，我使用的是`oicq`的分支`icqq`协议，我阅读了`icqq`的commit history，发现作者在 [这次提交](https://github.com/takayama-lily/oicq/commit/5448edf47eee6ea9f02f5e450c5ba917c7257899) 中将`EventEmitter`类更换为了`TripTrap`，这才使得我无法调用相关的API
