### ISSUE TITLE
禁止登陆

### ISSUE THREAD

**Issue by grutty-sf** [takayama-lily/oicq#86]
[禁止登录]当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再
试   QQ是可以正常登陆的，换个账号也不行

**Comment by takayama-lily** [comment]
该问题的原因目前尚未完全查明。
一般是登录的IP不在常用登录地，以及新账号尤其容易发生。
已知在目标机器上电脑QQ登录挂一段时间可解决。

**Comment by grutty-sf** [comment]
@takayama-lily 不过之前账号能登录，没遇过这种问题。今天刚遇到

**Comment by grutty-sf** [comment]
@takayama-lily 刚试了 第一次使用oicq登录的账号 会提示 [禁止登录]为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）

**Comment by grutty-sf** [comment]
@takayama-lily 用手机登录QQ后  再用oicq登录   会有 扫码验证设备信息。但再重新登录 又出现禁止登录了。

**Comment by takayama-lily** [comment]
> @takayama-lily 用手机登录QQ后  再用oicq登录   会有 扫码验证设备信息。但再重新登录 又出现禁止登录了。

将登录协议改为平板可以避免出现禁止登录。登录成功后再切换到手机协议

**Comment by takayama-lily** [comment]
[登录常见问题](https://github.com/takayama-lily/onebot/issues/12)
