### ISSUE TITLE
开源协议类型与 package.json 不一致

### ISSUE THREAD

**Issue by Steve-xmh** [takayama-lily/oicq#99]
![LICENSE 文件里的是 Apache License 2.0](https://user-images.githubusercontent.com/39523898/100640639-9f305d00-3371-11eb-8f65-a692b2b9e95d.png)
![package.json 和 npm 是 AGPL v3](https://user-images.githubusercontent.com/39523898/100640685-ab1c1f00-3371-11eb-8e3c-4b16389f2260.png)

**Comment by takayama-lily** [comment]
前两天刚从AGPL-3.0变更到Apache-2.0，还没发布到npm。
主要GPL类协议不太适合Nodejs程序，因为本身就以源码形式分发，反而会造成的不必要的传染。
